export const INVENTORY_PAGE_CONFIGS = {
  events: {
    key: "events",
    title: "Event Definitions",
    description: "Generic event contracts for future inventory integrations. No stock posting or operational workflow is implemented.",
    emptyMessage: "No event definitions found.",
    columns: [
      { key: "eventKey", header: "Event Key", field: "eventKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "direction", header: "Direction", field: "direction" },
      { key: "sourceScope", header: "Source Scope", field: "sourceScope" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
  },
  endpoints: {
    key: "endpoints",
    title: "Integration Endpoints",
    description: "Endpoint placeholders only. No transport execution, credentials, webhooks, or external side effects are implemented.",
    emptyMessage: "No integration endpoints found.",
    columns: [
      { key: "endpointKey", header: "Endpoint Key", field: "endpointKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "direction", header: "Direction", field: "direction" },
      { key: "transport", header: "Transport", field: "transport" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
  },
  routes: {
    key: "routes",
    title: "Event Routes",
    description: "Route placeholders connecting event contracts to endpoints. No delivery workflow is implemented.",
    emptyMessage: "No event routes found.",
    columns: [
      { key: "routeKey", header: "Route Key", field: "routeKey" },
      { key: "eventDefinitionId", header: "Event Definition", field: "eventDefinitionId" },
      { key: "endpointId", header: "Endpoint", field: "endpointId" },
      { key: "deliveryModePlaceholder", header: "Delivery Mode", field: "deliveryModePlaceholder" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
  },
  messages: {
    key: "messages",
    title: "Message Placeholders",
    description: "Integration message placeholders only. These records do not post stock, trigger delivery, or mutate source records.",
    emptyMessage: "No integration message placeholders found.",
    columns: [
      { key: "messageKey", header: "Message Key", field: "messageKey" },
      { key: "direction", header: "Direction", field: "direction" },
      { key: "status", header: "Status", field: "status" },
      { key: "sourceEntityType", header: "Source Type", field: "sourceEntityType" },
      { key: "externalReference", header: "External Reference", field: "externalReference" },
    ],
  },
  stockLedger: {
    key: "stockLedger",
    title: "Stock Ledger",
    description: "Append-only stock ledger entries posted through StockPostingService. This is the source of truth for stock quantities.",
    emptyMessage: "No stock ledger entries found.",
    columns: [
      { key: "postedAt", header: "Posted At", field: "postedAt" },
      { key: "documentTypeKey", header: "Document Type", field: "documentTypeKey" },
      { key: "movementTypeKey", header: "Movement", field: "movementTypeKey" },
      { key: "productId", header: "Product", field: "productId" },
      { key: "warehouseId", header: "Warehouse", field: "warehouseId" },
      { key: "locationId", header: "Location", field: "locationId" },
      { key: "quantityDelta", header: "Delta", field: "quantityDelta" },
      { key: "direction", header: "Direction", field: "direction" },
    ],
  },
  stockBalances: {
    key: "stockBalances",
    title: "Stock Balances",
    description: "Read-only current balance cache derived from stock_ledger_entries. It is not a source of truth.",
    emptyMessage: "No stock balances found.",
    columns: [
      { key: "productId", header: "Product", field: "productId" },
      { key: "warehouseId", header: "Warehouse", field: "warehouseId" },
      { key: "locationId", header: "Location", field: "locationId" },
      { key: "quantityOnHand", header: "On Hand", field: "quantityOnHand" },
      { key: "quantityReserved", header: "Reserved", field: "quantityReserved" },
      { key: "quantityAvailable", header: "Available", field: "quantityAvailable" },
      { key: "lastMovementAt", header: "Last Movement", field: "lastMovementAt" },
    ],
  },
  postingBatches: {
    key: "postingBatches",
    title: "Posting Batches",
    description: "Read-only posting operation records with idempotency and reversal foundations.",
    emptyMessage: "No stock posting batches found.",
    columns: [
      { key: "postedAt", header: "Posted At", field: "postedAt" },
      { key: "status", header: "Status", field: "status" },
      { key: "documentId", header: "Document", field: "documentId" },
      { key: "idempotencyKey", header: "Idempotency Key", field: "idempotencyKey" },
      { key: "correlationId", header: "Correlation", field: "correlationId" },
      { key: "reversedAt", header: "Reversed At", field: "reversedAt" },
    ],
  },
} as const;
