import { defineAppManifest } from "@/platform/app-registry/public-api";
import { PLATFORM_PERMISSIONS } from "@/platform/permissions/public-api";

export const ADMINISTRATION_PERMISSION_LIST = [
  PLATFORM_PERMISSIONS.accessAdmin,
  PLATFORM_PERMISSIONS.readUsers,
  PLATFORM_PERMISSIONS.manageUsers,
  PLATFORM_PERMISSIONS.readMemberships,
  PLATFORM_PERMISSIONS.manageMemberships,
  PLATFORM_PERMISSIONS.manageRoles,
  PLATFORM_PERMISSIONS.readPermissions,
  PLATFORM_PERMISSIONS.readAuditLog,
  PLATFORM_PERMISSIONS.manageTenant,
  PLATFORM_PERMISSIONS.manageBranches,
] as const;

export const administrationAppManifest = defineAppManifest({
  capabilities: [
    { key: "admin-users", requiredPermission: PLATFORM_PERMISSIONS.readUsers, type: "route" },
    { key: "admin-roles", requiredPermission: PLATFORM_PERMISSIONS.manageRoles, type: "route" },
    { key: "admin-permissions", requiredPermission: PLATFORM_PERMISSIONS.readPermissions, type: "route" },
    { key: "admin-access", requiredPermission: PLATFORM_PERMISSIONS.manageMemberships, type: "setting" },
  ],
  category: "platform",
  commands: [
    {
      actionType: "open-page",
      appKey: "administration",
      category: "navigation",
      href: "/erp/admin/invitations?create=1",
      key: "administration.invite-user.open",
      label: "Invite User",
      order: 11,
      requiredPermission: PLATFORM_PERMISSIONS.manageUsers,
      scope: "app",
      supportedExperiences: ["erp"],
    },
    {
      actionType: "open-page",
      appKey: "administration",
      category: "navigation",
      href: "/erp/admin/users",
      key: "administration.users.open",
      label: "Open User Administration",
      order: 10,
      requiredPermission: PLATFORM_PERMISSIONS.readUsers,
      scope: "global",
      supportedExperiences: ["erp"],
    },
  ],
  dashboards: [],
  dependencies: [{ appKey: "platform", reason: "Uses Platform security, RBAC, tenancy, audit, and app registry contracts." }],
  description: "Administration hub for operational users, roles, permissions, invitations, app access, and data scopes.",
  experiences: ["erp"],
  icon: "shield-check",
  key: "administration",
  name: "Administration",
  navigation: [
    {
      appKey: "administration",
      href: "/erp/admin/users",
      key: "administration.launcher",
      kind: "app",
      label: "Administration",
      order: 90,
      placement: "app-launcher",
      requiredPermission: PLATFORM_PERMISSIONS.accessAdmin,
      supportedExperiences: ["erp"],
    },
  ],
  permissions: [PLATFORM_PERMISSIONS.accessAdmin],
  prints: [],
  quickActions: [
    {
      appKey: "administration",
      commandKey: "administration.invite-user.open",
      href: "/erp/admin/invitations?create=1",
      key: "administration.invite-user",
      label: "Invite User",
      order: 1,
      requiredPermission: PLATFORM_PERMISSIONS.manageUsers,
      scope: "app",
      supportedExperiences: ["erp"],
    },
  ],
  reports: [],
  routes: [
    {
      experience: "erp",
      key: "administration.users",
      label: "Users",
      path: "/erp/admin/users",
      requiredPermission: PLATFORM_PERMISSIONS.readUsers,
    },
    {
      experience: "erp",
      key: "administration.roles",
      label: "Roles",
      path: "/erp/admin/roles",
      requiredPermission: PLATFORM_PERMISSIONS.manageRoles,
    },
    {
      experience: "erp",
      key: "administration.permissions",
      label: "Permissions",
      path: "/erp/admin/permissions",
      requiredPermission: PLATFORM_PERMISSIONS.readPermissions,
    },
    {
      experience: "erp",
      key: "administration.invitations",
      label: "Invitations",
      path: "/erp/admin/invitations",
      requiredPermission: PLATFORM_PERMISSIONS.manageUsers,
    },
    {
      experience: "erp",
      key: "administration.access",
      label: "Access",
      path: "/erp/admin/access",
      requiredPermission: PLATFORM_PERMISSIONS.manageMemberships,
    },
  ],
  sensitiveData: "restricted",
  settings: [
    { key: "admin-access-policy", requiredPermission: PLATFORM_PERMISSIONS.manageTenant, type: "setting" },
  ],
  version: "1.0.0",
});
