export type WorkspaceAppStatus =
  | "ready"
  | "in-development"
  | "beta"
  | "planned"
  | "disabled"
  | "coming-soon"
  | "not-licensed"
  | "not-installed";

export type WorkspaceAppKind = "business" | "platform";

export type WorkspaceCatalogApp = Readonly<{
  key: string;
  name: string;
  shortName?: string;
  description: string;
  kind: WorkspaceAppKind;
  category: string;
  icon: string;
  gradient: string;
  status: WorkspaceAppStatus;
  phase?: string;
  dependencies?: readonly string[];
  estimatedRelease?: string;
  href?: string;
  docsHref?: string;
  order: number;
}>;

export const WORKSPACE_VERSION = "1.0.0";
export const WORKSPACE_LAST_UPDATE = "2026-06-27";
export const WORKSPACE_STORAGE_KEY = "nexora.workspace.preferences.v1";

export const PLANNED_BUSINESS_APPS = [
  {
    category: "procurement",
    dependencies: ["Inventory Foundation", "Manufacturing Review"],
    description: "Supplier requests, purchase orders, receiving, landed costs, and procurement controls.",
    docsHref: "/docs/apps/purchasing",
    estimatedRelease: "After UI Phase",
    gradient: "from-amber-500/20 via-orange-500/10 to-transparent",
    icon: "shopping-cart",
    key: "purchasing",
    kind: "business",
    name: "Purchasing",
    order: 110,
    phase: "Phase 2",
    status: "planned",
  },
  {
    category: "sales",
    dependencies: ["Inventory Foundation", "Customer Portal Contract"],
    description: "Quotations, sales orders, invoicing readiness, fulfillment, and customer commitments.",
    docsHref: "/docs/apps/sales",
    estimatedRelease: "After Procurement Phase",
    gradient: "from-sky-500/20 via-blue-500/10 to-transparent",
    icon: "badge-dollar-sign",
    key: "sales",
    kind: "business",
    name: "Sales",
    order: 120,
    phase: "Phase 2",
    status: "planned",
  },
  {
    category: "sales",
    dependencies: ["Party Foundation", "Sales Foundation"],
    description: "Accounts, opportunities, activities, lead routing, and commercial follow-up.",
    docsHref: "/docs/apps/crm",
    estimatedRelease: "After Sales Foundation",
    gradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    icon: "users",
    key: "crm",
    kind: "business",
    name: "CRM",
    order: 130,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "hr",
    dependencies: ["Employee Directory", "Security Foundation"],
    description: "Employee records, organization structures, leave readiness, and workforce documents.",
    docsHref: "/docs/apps/hr",
    estimatedRelease: "After Enterprise Access Phase",
    gradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    icon: "id-card",
    key: "hr",
    kind: "business",
    name: "HR",
    order: 140,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "hr",
    dependencies: ["HR Foundation", "Finance Foundation"],
    description: "Payroll definitions, pay runs, payroll posting readiness, and compliance exports.",
    docsHref: "/docs/apps/payroll",
    estimatedRelease: "After HR Foundation",
    gradient: "from-emerald-500/20 via-green-500/10 to-transparent",
    icon: "wallet-cards",
    key: "payroll",
    kind: "business",
    name: "Payroll",
    order: 150,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "service",
    dependencies: ["Inventory Foundation", "Help Desk Foundation"],
    description: "Service orders, service contracts, technician assignments, and warranty readiness.",
    docsHref: "/docs/apps/service",
    estimatedRelease: "After Help Desk Phase",
    gradient: "from-cyan-500/20 via-teal-500/10 to-transparent",
    icon: "wrench",
    key: "service",
    kind: "business",
    name: "Service",
    order: 160,
    phase: "Phase 4",
    status: "planned",
  },
  {
    category: "operations",
    dependencies: ["Assets Foundation", "Maintenance Foundation"],
    description: "Vehicle records, assignments, fuel, service history, and fleet compliance readiness.",
    docsHref: "/docs/apps/fleet",
    estimatedRelease: "After Assets Phase",
    gradient: "from-indigo-500/20 via-blue-500/10 to-transparent",
    icon: "truck",
    key: "fleet",
    kind: "business",
    name: "Fleet",
    order: 170,
    phase: "Phase 4",
    status: "planned",
  },
  {
    category: "operations",
    dependencies: ["Assets Foundation", "Sales Foundation"],
    description: "Rental contracts, availability, returns, billing readiness, and utilization controls.",
    docsHref: "/docs/apps/rental",
    estimatedRelease: "After Assets Phase",
    gradient: "from-lime-500/20 via-green-500/10 to-transparent",
    icon: "repeat",
    key: "rental",
    kind: "business",
    name: "Rental",
    order: 180,
    phase: "Phase 4",
    status: "planned",
  },
  {
    category: "operations",
    dependencies: ["Finance Foundation", "Document Foundation"],
    description: "Project setup, budgets, milestones, task coordination, and cost visibility readiness.",
    docsHref: "/docs/apps/projects",
    estimatedRelease: "After Finance UI Phase",
    gradient: "from-fuchsia-500/20 via-purple-500/10 to-transparent",
    icon: "folder-kanban",
    key: "projects",
    kind: "business",
    name: "Projects",
    order: 190,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "manufacturing",
    dependencies: ["Manufacturing Foundation", "Inventory Quality Hooks"],
    description: "Quality checks, nonconformance, inspections, corrective actions, and traceability.",
    docsHref: "/docs/apps/quality",
    estimatedRelease: "After Manufacturing Review",
    gradient: "from-teal-500/20 via-cyan-500/10 to-transparent",
    icon: "shield-check",
    key: "quality",
    kind: "business",
    name: "Quality",
    order: 200,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "operations",
    dependencies: ["Assets Foundation", "Inventory Foundation"],
    description: "Preventive maintenance, work requests, spare parts readiness, and asset service history.",
    docsHref: "/docs/apps/maintenance",
    estimatedRelease: "After Assets Phase",
    gradient: "from-orange-500/20 via-amber-500/10 to-transparent",
    icon: "hammer",
    key: "maintenance",
    kind: "business",
    name: "Maintenance",
    order: 210,
    phase: "Phase 4",
    status: "planned",
  },
  {
    category: "operations",
    dependencies: ["Finance Foundation", "Maintenance Foundation"],
    description: "Asset register, capitalization readiness, custody, depreciation hooks, and lifecycle controls.",
    docsHref: "/docs/apps/assets",
    estimatedRelease: "After Finance UI Phase",
    gradient: "from-stone-500/20 via-zinc-500/10 to-transparent",
    icon: "package-check",
    key: "assets",
    kind: "business",
    name: "Assets",
    order: 220,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "platform",
    dependencies: ["Document Foundation", "Audit Foundation"],
    description: "Enterprise files, document lifecycles, retention, approvals, and controlled attachments.",
    docsHref: "/docs/apps/document-management",
    estimatedRelease: "After UI Foundation",
    gradient: "from-blue-500/20 via-slate-500/10 to-transparent",
    icon: "files",
    key: "document-management",
    kind: "business",
    name: "Document Management",
    order: 230,
    phase: "Phase 2",
    status: "planned",
  },
  {
    category: "service",
    dependencies: ["Notification Foundation", "Employee Portal Contract"],
    description: "Tickets, queues, SLA readiness, support workflows, and internal service operations.",
    docsHref: "/docs/apps/help-desk",
    estimatedRelease: "After Notification UI Phase",
    gradient: "from-red-500/20 via-rose-500/10 to-transparent",
    icon: "life-buoy",
    key: "help-desk",
    kind: "business",
    name: "Help Desk",
    order: 240,
    phase: "Phase 3",
    status: "planned",
  },
  {
    category: "sales",
    dependencies: ["Inventory Foundation", "Sales Foundation"],
    description: "Point of sale sessions, cash control readiness, item lookup, and offline sync contracts.",
    docsHref: "/docs/apps/pos",
    estimatedRelease: "After Sales Phase",
    gradient: "from-yellow-500/20 via-amber-500/10 to-transparent",
    icon: "scan-barcode",
    key: "pos",
    kind: "business",
    name: "POS",
    order: 250,
    phase: "Phase 4",
    status: "planned",
  },
  {
    category: "platform",
    dependencies: ["App Registry", "Entitlement Contracts"],
    description: "App discovery, add-ons, extensions, licensing surfaces, and installation workflows.",
    docsHref: "/docs/apps/marketplace",
    estimatedRelease: "After Feature Flags Phase",
    gradient: "from-purple-500/20 via-indigo-500/10 to-transparent",
    icon: "store",
    key: "marketplace",
    kind: "business",
    name: "Marketplace",
    order: 260,
    phase: "Phase 5",
    status: "planned",
  },
  {
    category: "portal",
    dependencies: ["Sales Foundation", "Party Foundation"],
    description: "Customer self-service, statements, requests, documents, and portal notifications.",
    docsHref: "/docs/apps/customer-portal",
    estimatedRelease: "After Portal Phase",
    gradient: "from-sky-500/20 via-cyan-500/10 to-transparent",
    icon: "panel-top",
    key: "customer-portal",
    kind: "business",
    name: "Customer Portal",
    order: 270,
    phase: "Phase 5",
    status: "planned",
  },
  {
    category: "portal",
    dependencies: ["Purchasing Foundation", "Party Foundation"],
    description: "Supplier onboarding, RFQ collaboration, purchase documents, and shipment readiness.",
    docsHref: "/docs/apps/supplier-portal",
    estimatedRelease: "After Purchasing Phase",
    gradient: "from-orange-500/20 via-red-500/10 to-transparent",
    icon: "panel-right",
    key: "supplier-portal",
    kind: "business",
    name: "Supplier Portal",
    order: 280,
    phase: "Phase 5",
    status: "planned",
  },
  {
    category: "portal",
    dependencies: ["HR Foundation", "Notification Foundation"],
    description: "Employee self-service, tasks, documents, requests, announcements, and profile updates.",
    docsHref: "/docs/apps/employee-portal",
    estimatedRelease: "After HR Phase",
    gradient: "from-green-500/20 via-emerald-500/10 to-transparent",
    icon: "panel-left",
    key: "employee-portal",
    kind: "business",
    name: "Employee Portal",
    order: 290,
    phase: "Phase 5",
    status: "planned",
  },
] as const satisfies readonly WorkspaceCatalogApp[];

export const PLATFORM_APPS = [
  {
    category: "analytics",
    description: "Report catalog, exports, print readiness, and scheduled insight surfaces.",
    docsHref: "/docs/platform/reports",
    gradient: "from-blue-500/20 via-cyan-500/10 to-transparent",
    href: "/erp/reports",
    icon: "bar-chart-3",
    key: "platform-reports",
    kind: "platform",
    name: "Reports",
    order: 10,
    status: "ready",
  },
  {
    category: "analytics",
    description: "Reusable dashboard definitions, KPI widgets, and foundation readiness cards.",
    docsHref: "/docs/platform/dashboard",
    gradient: "from-indigo-500/20 via-blue-500/10 to-transparent",
    href: "/erp",
    icon: "layout-dashboard",
    key: "platform-dashboard",
    kind: "platform",
    name: "Dashboard",
    order: 20,
    status: "ready",
  },
  {
    category: "platform",
    description: "Permission-aware search across apps, commands, navigation, documents, and records.",
    docsHref: "/docs/platform/search",
    gradient: "from-slate-500/20 via-blue-500/10 to-transparent",
    icon: "search",
    key: "platform-search",
    kind: "platform",
    name: "Search",
    order: 30,
    status: "ready",
  },
  {
    category: "automation",
    dependencies: ["Event Outbox", "Job Foundation"],
    description: "Workflow triggers, background jobs, and business process automation readiness.",
    docsHref: "/docs/platform/automation",
    estimatedRelease: "After Job Runtime Phase",
    gradient: "from-purple-500/20 via-fuchsia-500/10 to-transparent",
    icon: "workflow",
    key: "platform-automation",
    kind: "platform",
    name: "Automation",
    order: 40,
    phase: "Platform Phase 2",
    status: "in-development",
  },
  {
    category: "ai",
    dependencies: ["Search Contracts", "Permission Engine"],
    description: "AI assistance contracts for commands, summaries, search help, and controlled automation.",
    docsHref: "/docs/platform/ai",
    estimatedRelease: "After Search UX Phase",
    gradient: "from-violet-500/20 via-indigo-500/10 to-transparent",
    icon: "sparkles",
    key: "platform-ai",
    kind: "platform",
    name: "AI",
    order: 50,
    phase: "Platform Phase 3",
    status: "planned",
  },
  {
    category: "platform",
    description: "Notification contracts, preferences, delivery mapping, and in-app notification surfaces.",
    docsHref: "/docs/platform/notifications",
    gradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    icon: "bell",
    key: "platform-notifications",
    kind: "platform",
    name: "Notifications",
    order: 60,
    status: "in-development",
  },
  {
    category: "platform",
    description: "Tenant, company, branch, app, and user workspace settings.",
    docsHref: "/docs/platform/settings",
    gradient: "from-zinc-500/20 via-slate-500/10 to-transparent",
    icon: "settings",
    key: "platform-settings",
    kind: "platform",
    name: "Settings",
    order: 70,
    status: "planned",
  },
  {
    category: "platform",
    description: "Administration hub for tenants, roles, users, entitlements, and app operations.",
    docsHref: "/docs/platform/administration",
    gradient: "from-red-500/20 via-orange-500/10 to-transparent",
    icon: "shield",
    key: "platform-administration",
    kind: "platform",
    name: "Administration",
    order: 80,
    status: "planned",
  },
  {
    category: "platform",
    description: "Audit event model, compliance metadata, and traceability for sensitive actions.",
    docsHref: "/docs/platform/audit",
    gradient: "from-stone-500/20 via-neutral-500/10 to-transparent",
    icon: "clipboard-check",
    key: "platform-audit",
    kind: "platform",
    name: "Audit",
    order: 90,
    status: "ready",
  },
  {
    category: "platform",
    description: "Health checks, platform telemetry readiness, operational signals, and review gates.",
    docsHref: "/docs/platform/monitoring",
    gradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
    icon: "activity",
    key: "platform-monitoring",
    kind: "platform",
    name: "Monitoring",
    order: 100,
    status: "planned",
  },
  {
    category: "integration",
    description: "Durable outbox, integration contracts, event delivery, and external system readiness.",
    docsHref: "/docs/platform/integrations",
    gradient: "from-cyan-500/20 via-blue-500/10 to-transparent",
    icon: "plug-zap",
    key: "platform-integrations",
    kind: "platform",
    name: "Integrations",
    order: 110,
    status: "ready",
  },
  {
    category: "platform",
    description: "Feature flag definitions, staged rollout controls, and gated app capabilities.",
    docsHref: "/docs/platform/feature-flags",
    gradient: "from-lime-500/20 via-green-500/10 to-transparent",
    icon: "flag",
    key: "platform-feature-flags",
    kind: "platform",
    name: "Feature Flags",
    order: 120,
    status: "ready",
  },
] as const satisfies readonly WorkspaceCatalogApp[];

export const WORKSPACE_APP_CATALOG = [
  ...PLANNED_BUSINESS_APPS,
  ...PLATFORM_APPS,
] as const satisfies readonly WorkspaceCatalogApp[];
