import { defineOxLookupProvider } from "./public-api";

export const OX_LOOKUP_PROVIDERS = [
  defineOxLookupProvider({
    entityType: "product",
    key: "inventory.products.lookup",
    hydrateProviderKey: "inventory.products.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "inventory.products",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: true,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: true,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "warehouse",
    key: "inventory.warehouses.lookup",
    hydrateProviderKey: "inventory.warehouses.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "inventory.warehouses",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "warehouse-location",
    key: "inventory.locations.lookup",
    hydrateProviderKey: "inventory.locations.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "inventory.locations",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: true,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: true,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "lot",
    key: "inventory.lots.lookup",
    hydrateProviderKey: "inventory.lots.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "inventory.lots",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: true,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: true,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "serial",
    key: "inventory.serials.lookup",
    hydrateProviderKey: "inventory.serials.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "inventory.serials",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: true,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: true,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "inventory-transaction",
    key: "inventory.transactions.lookup",
    hydrateProviderKey: "inventory.transactions.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "inventory.transactions",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: true,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "supplier",
    key: "purchasing.suppliers.lookup",
    hydrateProviderKey: "purchasing.suppliers.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "purchasing.suppliers",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "purchase-order",
    key: "purchasing.documents.lookup",
    hydrateProviderKey: "purchasing.documents.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "purchasing.documents",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "customer",
    key: "party.customers.lookup",
    hydrateProviderKey: "party.customers.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "party.customers",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "branch",
    key: "platform.branches.lookup",
    hydrateProviderKey: "platform.branches.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "platform.branches",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "user",
    key: "platform.users.lookup",
    hydrateProviderKey: "platform.users.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "platform.users",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "uom",
    key: "inventory.uoms.lookup",
    hydrateProviderKey: "inventory.uoms.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "inventory.uoms",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "employee",
    key: "hr.employees.lookup",
    hydrateProviderKey: "hr.employees.hydrate",
    minSearchLength: 2,
    pageSize: 25,
    searchProviderKey: "hr.employees",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "position",
    key: "hr.positions.lookup",
    hydrateProviderKey: "hr.positions.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "hr.positions",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: true,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
  defineOxLookupProvider({
    entityType: "org-unit",
    key: "hr.org-units.lookup",
    hydrateProviderKey: "hr.org-units.hydrate",
    minSearchLength: 1,
    pageSize: 25,
    searchProviderKey: "hr.org-units",
    supportsAsyncLoading: true,
    supportsBarcodeSearch: false,
    supportsFavorites: false,
    supportsKeyboardNavigation: true,
    supportsQrSearch: false,
    supportsRecent: true,
    supportsRemoteSearch: true,
    supportsSelectedRecordHydration: true,
  }),
] as const;

export type OxLookupProviderKey = (typeof OX_LOOKUP_PROVIDERS)[number]["key"];

export function getOxLookupProvider(key: string) {
  return OX_LOOKUP_PROVIDERS.find((provider) => provider.key === key) ?? null;
}
