import { definePermissionKey } from "@/platform/permissions/public-api";

export const INVENTORY_PERMISSIONS = {
  adjustmentsCreate: definePermissionKey("inventory.adjustments.create"),
  auditView: definePermissionKey("inventory.audit.view"),
  costIntegrationView: definePermissionKey("inventory.cost-integration.view"),
  eventsView: definePermissionKey("inventory.events.view"),
  eventsManage: definePermissionKey("inventory.events.manage"),
  financeIntegrationView: definePermissionKey("inventory.finance-integration.view"),
  importExportManage: definePermissionKey("inventory.import-export.manage"),
  integrationView: definePermissionKey("inventory.integration.view"),
  integrationManage: definePermissionKey("inventory.integration.manage"),
  locationsManage: definePermissionKey("inventory.locations.manage"),
  locationsView: definePermissionKey("inventory.locations.view"),
  lotsManage: definePermissionKey("inventory.lots.manage"),
  lotsView: definePermissionKey("inventory.lots.view"),
  movementsCreate: definePermissionKey("inventory.movements.create"),
  movementsView: definePermissionKey("inventory.movements.view"),
  openingBalancesImport: definePermissionKey("inventory.opening-balances.import"),
  productsManage: definePermissionKey("inventory.products.manage"),
  productsView: definePermissionKey("inventory.products.view"),
  reorderRulesManage: definePermissionKey("inventory.reorder-rules.manage"),
  reorderRulesView: definePermissionKey("inventory.reorder-rules.view"),
  reportsView: definePermissionKey("inventory.reports.view"),
  reservationsApprove: definePermissionKey("inventory.reservations.approve"),
  reservationsAudit: definePermissionKey("inventory.reservations.audit"),
  reservationsCancel: definePermissionKey("inventory.reservations.cancel"),
  reservationsConsume: definePermissionKey("inventory.reservations.consume"),
  reservationsCreate: definePermissionKey("inventory.reservations.create"),
  reservationsRelease: definePermissionKey("inventory.reservations.release"),
  reservationsManage: definePermissionKey("inventory.reservations.manage"),
  reservationsView: definePermissionKey("inventory.reservations.view"),
  searchView: definePermissionKey("inventory.search.view"),
  serialsManage: definePermissionKey("inventory.serials.manage"),
  serialsView: definePermissionKey("inventory.serials.view"),
  stockView: definePermissionKey("inventory.stock.view"),
  stockPost: definePermissionKey("inventory.stock.post"),
  stockReverse: definePermissionKey("inventory.stock.reverse"),
  stockSnapshot: definePermissionKey("inventory.stock.snapshot"),
  stockManageRules: definePermissionKey("inventory.stock.manage-rules"),
  transactionView: definePermissionKey("inventory.transaction.view"),
  transactionCreate: definePermissionKey("inventory.transaction.create"),
  transactionUpdate: definePermissionKey("inventory.transaction.update"),
  transactionSubmit: definePermissionKey("inventory.transaction.submit"),
  transactionPost: definePermissionKey("inventory.transaction.post"),
  transactionCancel: definePermissionKey("inventory.transaction.cancel"),
  transactionReverse: definePermissionKey("inventory.transaction.reverse"),
  transfersComplete: definePermissionKey("inventory.transfers.complete"),
  transfersRequest: definePermissionKey("inventory.transfers.request"),
  uomsManage: definePermissionKey("inventory.uoms.manage"),
  uomsView: definePermissionKey("inventory.uoms.view"),
  warehousesManage: definePermissionKey("inventory.warehouses.manage"),
  warehousesView: definePermissionKey("inventory.warehouses.view"),
  cycleCountView: definePermissionKey("inventory.cycle-count.view"),
  cycleCountManage: definePermissionKey("inventory.cycle-count.manage"),
  cycleCountPost: definePermissionKey("inventory.cycle-count.post"),
} as const;

export const INVENTORY_PERMISSION_LIST = Object.values(INVENTORY_PERMISSIONS);
