export const PRODUCT_PAGE_CONFIG = {
  key: "products",
  title: "Products",
  description: "Manage reusable product master records for sales, purchasing, inventory, and production planning.",
  basePath: "/erp/master-data/products",
  columns: [
    { key: "sku", header: "Sku", field: "sku" },
    { key: "barcode", header: "Barcode", field: "barcode" },
    { key: "nameAr", header: "Name Ar", field: "nameAr" },
    { key: "nameEn", header: "Name En", field: "nameEn" },
    { key: "categoryId", header: "Category", field: "categoryId" },
    { key: "brandId", header: "Brand", field: "brandId" },
    { key: "productType", header: "Product Type", field: "productType" },
    { key: "unitId", header: "Unit", field: "unitId" },
    { key: "isActive", header: "Is Active", field: "isActive" },
  ],
  formFields: [
    { name: "sku", label: "SKU", type: "text", isRequired: true },
    { name: "barcode", label: "Barcode", type: "text", isRequired: false },
    { name: "nameAr", label: "Arabic name", type: "text", isRequired: true },
    { name: "nameEn", label: "English name", type: "text", isRequired: true },
    { name: "categoryId", label: "Category ID", type: "text", isRequired: false },
    { name: "brandId", label: "Brand ID", type: "text", isRequired: false },
    { name: "productType", label: "Product type", type: "text", isRequired: true },
    { name: "unitId", label: "Unit of measure ID", type: "text", isRequired: false },
    { name: "defaultPurchaseUnitId", label: "Default purchase unit ID", type: "text", isRequired: false },
    { name: "defaultSalesUnitId", label: "Default sales unit ID", type: "text", isRequired: false },
    { name: "isManufacturable", label: "Manufacturable", type: "checkbox", isRequired: false },
    { name: "isStockable", label: "Stockable flag", type: "checkbox", isRequired: false },
    { name: "isSellable", label: "Sellable flag", type: "checkbox", isRequired: false },
    { name: "isPurchasable", label: "Purchasable flag", type: "checkbox", isRequired: false },
  ],
} as const;
