import { MANUFACTURING_PERMISSIONS } from "../../permissions/permission-registry";
import type { ManufacturingResourceDefinition, ManufacturingResourceKey } from "../../application/types";

const basePath = "/erp/manufacturing";

export const MANUFACTURING_RESOURCE_DEFINITIONS = {
  "production-lines": {
    key: "production-lines",
    title: "Production Lines",
    singularTitle: "Production Line",
    description: "Factory line structure prepared for future production sessions.",
    basePath: `${basePath}/production-lines`,
    tableName: "production_lines",
    selectColumns: "id, tenant_id, branch_id, line_code, name_ar, name_en, display_order, daily_working_hours, max_workers, status, is_packaging_line, is_injection_line, default_work_center_id, current_product_id, daily_target_qty, is_active, created_at, updated_at, version",
    searchColumns: ["line_code", "name_ar", "name_en"],
    columns: [
      { key: "lineCode", header: "Line Code", field: "lineCode" },
      { key: "nameAr", header: "Arabic Name", field: "nameAr" },
      { key: "nameEn", header: "English Name", field: "nameEn" },
      { key: "status", header: "Status", field: "status" },
      { key: "dailyTargetQty", header: "Daily Target", field: "dailyTargetQty" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "lineCode", label: "Line code", type: "text", isRequired: true },
      { name: "nameAr", label: "Arabic name", type: "text", isRequired: true },
      { name: "nameEn", label: "English name", type: "text", isRequired: true },
      { name: "branchId", label: "Branch ID", type: "text", isRequired: true },
      { name: "displayOrder", label: "Display order", type: "number", isRequired: false },
      { name: "dailyWorkingHours", label: "Daily working hours", type: "number", isRequired: false },
      { name: "maxWorkers", label: "Max workers", type: "number", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isPackagingLine", label: "Packaging line", type: "checkbox", isRequired: false },
      { name: "isInjectionLine", label: "Injection line", type: "checkbox", isRequired: false },
      { name: "defaultWorkCenterId", label: "Default work center ID", type: "text", isRequired: false },
      { name: "currentProductId", label: "Current product placeholder ID", type: "text", isRequired: false },
      { name: "dailyTargetQty", label: "Daily target placeholder", type: "number", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.linesView,
    managePermission: MANUFACTURING_PERMISSIONS.linesManage,
    createdEventName: "manufacturing.line.created",
    updatedEventName: "manufacturing.line.updated",
    aggregateType: "manufacturing_line",
  },
  "work-centers": {
    key: "work-centers",
    title: "Work Centers",
    singularTitle: "Work Center",
    description: "Engineering capacity centers used by future routings and sessions.",
    basePath: `${basePath}/work-centers`,
    tableName: "work_centers",
    selectColumns: "id, tenant_id, branch_id, code, name_ar, name_en, capacity, standard_hours, cost_center_id, is_active, created_at, updated_at, version",
    searchColumns: ["code", "name_ar", "name_en"],
    columns: [
      { key: "code", header: "Code", field: "code" },
      { key: "nameAr", header: "Arabic Name", field: "nameAr" },
      { key: "nameEn", header: "English Name", field: "nameEn" },
      { key: "capacity", header: "Capacity", field: "capacity" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "code", label: "Code", type: "text", isRequired: true },
      { name: "nameAr", label: "Arabic name", type: "text", isRequired: true },
      { name: "nameEn", label: "English name", type: "text", isRequired: true },
      { name: "branchId", label: "Branch ID", type: "text", isRequired: true },
      { name: "capacity", label: "Capacity", type: "number", isRequired: false },
      { name: "standardHours", label: "Standard hours", type: "number", isRequired: false },
      { name: "costCenterId", label: "Cost center placeholder ID", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workCentersView,
    managePermission: MANUFACTURING_PERMISSIONS.workCentersManage,
    aggregateType: "work_center",
  },
  "manufacturing-profiles": {
    key: "manufacturing-profiles",
    title: "Manufacturing Profiles",
    singularTitle: "Manufacturing Profile",
    description: "Employee-backed manufacturing operational profiles without duplicated person data.",
    basePath: `${basePath}/manufacturing-profiles`,
    tableName: "manufacturing_profiles",
    selectColumns: "id, tenant_id, branch_id, employee_id, manufacturing_code, default_line_id, default_role, skill_level, production_enabled, notes, is_active, created_at, updated_at, version",
    searchColumns: ["manufacturing_code", "skill_level"],
    columns: [
      { key: "manufacturingCode", header: "Manufacturing Code", field: "manufacturingCode" },
      { key: "employeeId", header: "Employee", field: "employeeId" },
      { key: "defaultRole", header: "Default Role", field: "defaultRole" },
      { key: "productionEnabled", header: "Production Enabled", field: "productionEnabled" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "branchId", label: "Branch ID", type: "text", isRequired: true },
      { name: "employeeId", label: "Employee reference ID", type: "text", isRequired: true },
      { name: "manufacturingCode", label: "Manufacturing code", type: "text", isRequired: true },
      { name: "defaultLineId", label: "Default line ID", type: "text", isRequired: false },
      { name: "defaultRole", label: "Default role", type: "text", isRequired: true },
      { name: "skillLevel", label: "Skill level", type: "text", isRequired: false },
      { name: "productionEnabled", label: "Production enabled", type: "checkbox", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.workersManage,
    createdEventName: "manufacturing.worker.created",
    aggregateType: "manufacturing_profile",
  },
  "line-assignments": {
    key: "line-assignments",
    title: "Line Assignments",
    singularTitle: "Line Assignment",
    description: "Permanent and placeholder daily manufacturing profile-to-line assignments.",
    basePath: `${basePath}/line-assignments`,
    tableName: "manufacturing_line_assignments",
    selectColumns: "id, tenant_id, branch_id, manufacturing_profile_id, production_line_id, shift_id, labor_role, counts_toward_production, assignment_type, start_date, end_date, notes, is_active, created_at, updated_at, version",
    searchColumns: ["labor_role", "assignment_type"],
    columns: [
      { key: "manufacturingProfileId", header: "Manufacturing Profile", field: "manufacturingProfileId" },
      { key: "productionLineId", header: "Production Line", field: "productionLineId" },
      { key: "laborRole", header: "Labor Role", field: "laborRole" },
      { key: "countsTowardProduction", header: "Counts Toward Production", field: "countsTowardProduction" },
      { key: "assignmentType", header: "Assignment Type", field: "assignmentType" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "branchId", label: "Branch ID", type: "text", isRequired: true },
      { name: "manufacturingProfileId", label: "Manufacturing profile ID", type: "text", isRequired: true },
      { name: "productionLineId", label: "Production line ID", type: "text", isRequired: true },
      { name: "shiftId", label: "Shift ID", type: "text", isRequired: false },
      { name: "laborRole", label: "Labor role", type: "text", isRequired: true },
      { name: "countsTowardProduction", label: "Counts toward production", type: "checkbox", isRequired: false },
      { name: "assignmentType", label: "Assignment type", type: "text", isRequired: true },
      { name: "startDate", label: "Start date", type: "date", isRequired: true },
      { name: "endDate", label: "End date", type: "date", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.assignmentsManage,
    createdEventName: "manufacturing.worker.assigned",
    aggregateType: "manufacturing_line_assignment",
  },
  "production-standards": {
    key: "production-standards",
    title: "Production Standards",
    singularTitle: "Production Standard",
    description: "Product-line-shift target standards used later to distribute targets across counted production workers.",
    basePath: `${basePath}/production-standards`,
    tableName: "production_standards",
    selectColumns: "id, tenant_id, branch_id, product_id, production_line_id, shift_id, daily_target_qty, hourly_target_qty, standard_cycle_time_seconds, standard_crew_size, efficiency_target_percent, effective_from, effective_to, notes, is_active, created_at, updated_at, version",
    searchColumns: ["product_id", "production_line_id"],
    columns: [
      { key: "productId", header: "Product", field: "productId" },
      { key: "productionLineId", header: "Production Line", field: "productionLineId" },
      { key: "shiftId", header: "Shift", field: "shiftId" },
      { key: "dailyTargetQty", header: "Daily Target", field: "dailyTargetQty" },
      { key: "standardCrewSize", header: "Crew Size", field: "standardCrewSize" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "branchId", label: "Branch ID", type: "text", isRequired: true },
      { name: "productId", label: "Product ID", type: "text", isRequired: true },
      { name: "productionLineId", label: "Production line ID", type: "text", isRequired: true },
      { name: "shiftId", label: "Shift ID", type: "text", isRequired: false },
      { name: "dailyTargetQty", label: "Daily target quantity", type: "number", isRequired: true },
      { name: "hourlyTargetQty", label: "Hourly target quantity", type: "number", isRequired: false },
      { name: "standardCycleTimeSeconds", label: "Standard cycle time seconds", type: "number", isRequired: false },
      { name: "standardCrewSize", label: "Standard crew size", type: "number", isRequired: true },
      { name: "efficiencyTargetPercent", label: "Efficiency target percent", type: "number", isRequired: false },
      { name: "effectiveFrom", label: "Effective from", type: "date", isRequired: true },
      { name: "effectiveTo", label: "Effective to", type: "date", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.targetsManage,
    aggregateType: "production_standard",
  },
  boms: {
    key: "boms",
    title: "BOMs",
    singularTitle: "BOM",
    description: "Bill of material headers for manufacturable products. No material consumption is posted.",
    basePath: `${basePath}/boms`,
    tableName: "manufacturing_boms",
    selectColumns: "id, tenant_id, product_id, version_code, status, effective_from, effective_to, is_active, created_at, updated_at, version",
    searchColumns: ["version_code", "status"],
    columns: [
      { key: "productId", header: "Product", field: "productId" },
      { key: "versionCode", header: "Version", field: "versionCode" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "productId", label: "Product ID", type: "text", isRequired: true },
      { name: "versionCode", label: "Version", type: "text", isRequired: true },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "effectiveFrom", label: "Effective from", type: "date", isRequired: false },
      { name: "effectiveTo", label: "Effective to", type: "date", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.bomView,
    managePermission: MANUFACTURING_PERMISSIONS.bomManage,
    createdEventName: "manufacturing.bom.created",
    aggregateType: "manufacturing_bom",
  },
  "routing-plans": {
    key: "routing-plans",
    title: "Routing Plans",
    singularTitle: "Routing Plan",
    description: "Manufacturing engineering routing headers. No routing execution is implemented.",
    basePath: `${basePath}/routing-plans`,
    tableName: "manufacturing_routing_plans",
    selectColumns: "id, tenant_id, product_id, version_code, total_standard_time_seconds, total_man_time_seconds, target_unit_seconds, is_active, created_at, updated_at, version",
    searchColumns: ["version_code"],
    columns: [
      { key: "productId", header: "Product", field: "productId" },
      { key: "versionCode", header: "Version", field: "versionCode" },
      { key: "totalStandardTimeSeconds", header: "Std Seconds", field: "totalStandardTimeSeconds" },
      { key: "targetUnitSeconds", header: "Target Seconds", field: "targetUnitSeconds" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "productId", label: "Product ID", type: "text", isRequired: true },
      { name: "versionCode", label: "Version", type: "text", isRequired: true },
      { name: "totalStandardTimeSeconds", label: "Total standard time seconds", type: "number", isRequired: false },
      { name: "totalManTimeSeconds", label: "Total man time seconds", type: "number", isRequired: false },
      { name: "targetUnitSeconds", label: "Target unit seconds", type: "number", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.routingView,
    managePermission: MANUFACTURING_PERMISSIONS.routingManage,
    createdEventName: "manufacturing.routing.created",
    aggregateType: "manufacturing_routing",
  },
} satisfies Record<ManufacturingResourceKey, ManufacturingResourceDefinition>;

export const MANUFACTURING_RESOURCE_LIST = Object.values(MANUFACTURING_RESOURCE_DEFINITIONS);

export function parseManufacturingResourceKey(value: string): ManufacturingResourceKey {
  if (value in MANUFACTURING_RESOURCE_DEFINITIONS) return value as ManufacturingResourceKey;
  throw new Error(`Unsupported manufacturing resource: ${value}`);
}

export function getManufacturingResourceDefinition(key: ManufacturingResourceKey) {
  return MANUFACTURING_RESOURCE_DEFINITIONS[key];
}
