import { MANUFACTURING_PERMISSIONS } from "../../permissions/permission-registry";
import type { ManufacturingResourceDefinition, ManufacturingResourceKey } from "../../application/types";

const basePath = "/erp/manufacturing";

export const MANUFACTURING_RESOURCE_DEFINITIONS = {
  "manufacturing-products": {
    key: "manufacturing-products",
    title: "Manufacturing Products",
    singularTitle: "Manufacturing Product",
    description: "Products enabled for manufacturing execution facts.",
    basePath: `${basePath}/manufacturing-products`,
    tableName: "manufacturing_products",
    selectColumns: "id, tenant_id, company_id, branch_id, inventory_product_id, product_key, name, default_bom_key, default_routing_key, status, is_active, created_at, updated_at, version",
    searchColumns: ["product_key", "name", "status"],
    columns: [
      { key: "productKey", header: "Product Code", field: "productKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "PROD", scope: "company" }, name: "productKey", label: "Product Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "inventoryProductId", label: "Inventory product", type: "text", isRequired: false },
      { name: "defaultBomKey", label: "Default BOM key", type: "text", isRequired: false },
      { name: "defaultRoutingKey", label: "Default routing key", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.view,
    managePermission: MANUFACTURING_PERMISSIONS.manage,
    aggregateType: "manufacturing_product",
    scope: "company",
  },
  "production-lines": {
    key: "production-lines",
    title: "Production Lines",
    singularTitle: "Production Line",
    description: "Factory line structure used by DPR, targets, orders, and work orders.",
    basePath: `${basePath}/production-lines`,
    tableName: "manufacturing_lines",
    selectColumns: "id, tenant_id, company_id, branch_id, work_center_id, line_key, name, status, is_active, created_at, updated_at, version",
    searchColumns: ["line_key", "name", "status"],
    columns: [
      { key: "lineKey", header: "Line Code", field: "lineKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "LINE", scope: "branch" }, name: "lineKey", label: "Line Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "workCenterId", label: "Work center", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.linesView,
    managePermission: MANUFACTURING_PERMISSIONS.linesManage,
    createdEventName: "manufacturing.line.created",
    updatedEventName: "manufacturing.line.updated",
    aggregateType: "manufacturing_line",
    scope: "branch",
  },
  "work-centers": {
    key: "work-centers",
    title: "Work Centers",
    singularTitle: "Work Center",
    description: "Engineering capacity centers used by lines, workstations, and routing facts.",
    basePath: `${basePath}/work-centers`,
    tableName: "manufacturing_work_centers",
    selectColumns: "id, tenant_id, company_id, branch_id, work_center_key, name, capacity, cost_center_key, status, is_active, created_at, updated_at, version",
    searchColumns: ["work_center_key", "name", "status"],
    columns: [
      { key: "workCenterKey", header: "Code", field: "workCenterKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "capacity", header: "Capacity", field: "capacity" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "WC", scope: "branch" }, name: "workCenterKey", label: "Work Center Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "capacity", label: "Capacity", type: "number", isRequired: false },
      { name: "costCenterKey", label: "Cost center key", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workCentersView,
    managePermission: MANUFACTURING_PERMISSIONS.workCentersManage,
    aggregateType: "work_center",
    scope: "branch",
  },
  workstations: {
    key: "workstations",
    title: "Workstations",
    singularTitle: "Workstation",
    description: "Operational stations inside work centers and production lines.",
    basePath: `${basePath}/workstations`,
    tableName: "manufacturing_workstations",
    selectColumns: "id, tenant_id, company_id, branch_id, work_center_id, line_id, workstation_key, name, status, is_active, created_at, updated_at, version",
    searchColumns: ["workstation_key", "name", "status"],
    columns: [
      { key: "workstationKey", header: "Code", field: "workstationKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "workCenterId", header: "Work Center", field: "workCenterId" },
      { key: "lineId", header: "Line", field: "lineId" },
      { key: "status", header: "Status", field: "status" },
    ],
    formFields: [
      { autoCode: { prefix: "WS", scope: "branch" }, name: "workstationKey", label: "Workstation Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "workCenterId", label: "Work center", type: "text", isRequired: true },
      { name: "lineId", label: "Line", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workstationsView,
    managePermission: MANUFACTURING_PERMISSIONS.workstationsManage,
    aggregateType: "manufacturing_workstation",
    scope: "branch",
  },
  machines: {
    key: "machines",
    title: "Machines",
    singularTitle: "Machine",
    description: "Machine facts attached to work centers and workstations.",
    basePath: `${basePath}/machines`,
    tableName: "manufacturing_machines",
    selectColumns: "id, tenant_id, company_id, branch_id, work_center_id, workstation_id, machine_key, name, machine_hour_fact_ready, status, is_active, created_at, updated_at, version",
    searchColumns: ["machine_key", "name", "status"],
    columns: [
      { key: "machineKey", header: "Code", field: "machineKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "workCenterId", header: "Work Center", field: "workCenterId" },
      { key: "workstationId", header: "Workstation", field: "workstationId" },
      { key: "status", header: "Status", field: "status" },
    ],
    formFields: [
      { autoCode: { prefix: "MCH", scope: "branch" }, name: "machineKey", label: "Machine Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "workCenterId", label: "Work center", type: "text", isRequired: false },
      { name: "workstationId", label: "Workstation", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.machinesView,
    managePermission: MANUFACTURING_PERMISSIONS.machinesManage,
    aggregateType: "manufacturing_machine",
    scope: "branch",
  },
  operations: {
    key: "operations",
    title: "Operations",
    singularTitle: "Operation",
    description: "Routing operation definitions for production facts only.",
    basePath: `${basePath}/operations`,
    tableName: "manufacturing_operations",
    selectColumns: "id, tenant_id, company_id, branch_id, operation_key, name, operation_kind, standard_minutes, quality_readiness_only, status, is_active, created_at, updated_at, version",
    searchColumns: ["operation_key", "name", "operation_kind", "status"],
    columns: [
      { key: "operationKey", header: "Code", field: "operationKey" },
      { key: "name", header: "Name", field: "name" },
      { key: "operationKind", header: "Kind", field: "operationKind" },
      { key: "standardMinutes", header: "Std Minutes", field: "standardMinutes" },
      { key: "status", header: "Status", field: "status" },
    ],
    formFields: [
      { autoCode: { prefix: "OP", scope: "company" }, name: "operationKey", label: "Operation Code", type: "text", isRequired: true },
      { name: "name", label: "Name", type: "text", isRequired: true },
      { name: "operationKind", label: "Kind", type: "text", isRequired: true },
      { name: "standardMinutes", label: "Standard minutes", type: "number", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.operationsView,
    managePermission: MANUFACTURING_PERMISSIONS.operationsManage,
    aggregateType: "manufacturing_operation",
    scope: "company",
  },
  "manufacturing-profiles": {
    key: "manufacturing-profiles",
    title: "Manufacturing Profiles",
    singularTitle: "Manufacturing Profile",
    description: "Employee-backed manufacturing operational profiles without duplicated person data.",
    basePath: `${basePath}/manufacturing-profiles`,
    tableName: "manufacturing_profiles",
    selectColumns: "id, tenant_id, company_id, branch_id, employee_id, manufacturing_code, default_line_id, default_role, skill_level, production_enabled, notes, is_active, created_at, updated_at, version",
    searchColumns: ["manufacturing_code", "skill_level"],
    columns: [
      { key: "manufacturingCode", header: "Manufacturing Code", field: "manufacturingCode" },
      { key: "employeeId", header: "Employee", field: "employeeId" },
      { key: "defaultRole", header: "Default Role", field: "defaultRole" },
      { key: "productionEnabled", header: "Production Enabled", field: "productionEnabled" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "employeeId", label: "Employee", type: "text", isRequired: true },
      { autoCode: { prefix: "MFG", scope: "branch", storageCase: "upper" }, name: "manufacturingCode", label: "Manufacturing Code", type: "text", isRequired: true },
      { name: "defaultLineId", label: "Default line", type: "text", isRequired: false },
      { name: "defaultRole", label: "Default role", type: "text", isRequired: true },
      { name: "skillLevel", label: "Skill level", type: "text", isRequired: false },
      { name: "productionEnabled", label: "Production enabled", type: "checkbox", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.workersManage,
    createdEventName: "manufacturing.worker.created",
    aggregateType: "manufacturing_profile",
    scope: "branch",
  },
  "line-assignments": {
    key: "line-assignments",
    title: "Line Assignments",
    singularTitle: "Line Assignment",
    description: "Permanent and placeholder daily manufacturing profile-to-line assignments.",
    basePath: `${basePath}/line-assignments`,
    tableName: "manufacturing_line_assignments",
    selectColumns: "id, tenant_id, company_id, branch_id, manufacturing_profile_id, production_line_id, shift_id, labor_role, counts_toward_production, assignment_type, start_date, end_date, notes, is_active, created_at, updated_at, version",
    searchColumns: ["labor_role", "assignment_type"],
    columns: [
      { key: "manufacturingProfileId", header: "Manufacturing Profile", field: "manufacturingProfileId" },
      { key: "productionLineId", header: "Production Line", field: "productionLineId" },
      { key: "laborRole", header: "Labor Role", field: "laborRole" },
      { key: "countsTowardProduction", header: "Counts Toward Production", field: "countsTowardProduction" },
      { key: "assignmentType", header: "Assignment Type", field: "assignmentType" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "manufacturingProfileId", label: "Manufacturing profile", type: "text", isRequired: true },
      { name: "productionLineId", label: "Production line", type: "text", isRequired: true },
      { name: "shiftId", label: "Shift", type: "text", isRequired: false },
      { name: "laborRole", label: "Labor role", type: "text", isRequired: true },
      { name: "countsTowardProduction", label: "Counts toward production", type: "checkbox", isRequired: false },
      { name: "assignmentType", label: "Assignment type", type: "text", isRequired: true },
      { name: "startDate", label: "Start date", type: "date", isRequired: true },
      { name: "endDate", label: "End date", type: "date", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.assignmentsManage,
    createdEventName: "manufacturing.worker.assigned",
    aggregateType: "manufacturing_line_assignment",
    scope: "branch",
  },
  "production-standards": {
    key: "production-standards",
    title: "Production Standards",
    singularTitle: "Production Standard",
    description: "Product-line-shift target standards used later to distribute targets across counted production workers.",
    basePath: `${basePath}/production-standards`,
    tableName: "production_standards",
    selectColumns: "id, tenant_id, company_id, branch_id, product_id, production_line_id, shift_id, daily_target_qty, hourly_target_qty, standard_cycle_time_seconds, standard_crew_size, efficiency_target_percent, effective_from, effective_to, notes, is_active, created_at, updated_at, version",
    searchColumns: ["product_id", "production_line_id"],
    columns: [
      { key: "productId", header: "Product", field: "productId" },
      { key: "productionLineId", header: "Production Line", field: "productionLineId" },
      { key: "shiftId", header: "Shift", field: "shiftId" },
      { key: "dailyTargetQty", header: "Daily Target", field: "dailyTargetQty" },
      { key: "standardCrewSize", header: "Crew Size", field: "standardCrewSize" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { name: "productId", label: "Product", type: "text", isRequired: true },
      { name: "productionLineId", label: "Production line", type: "text", isRequired: true },
      { name: "shiftId", label: "Shift", type: "text", isRequired: false },
      { name: "dailyTargetQty", label: "Daily target quantity", type: "number", isRequired: true },
      { name: "hourlyTargetQty", label: "Hourly target quantity", type: "number", isRequired: false },
      { name: "standardCycleTimeSeconds", label: "Standard cycle time seconds", type: "number", isRequired: false },
      { name: "standardCrewSize", label: "Standard crew size", type: "number", isRequired: true },
      { name: "efficiencyTargetPercent", label: "Efficiency target percent", type: "number", isRequired: false },
      { name: "effectiveFrom", label: "Effective from", type: "date", isRequired: true },
      { name: "effectiveTo", label: "Effective to", type: "date", isRequired: false },
      { name: "notes", label: "Notes", type: "text", isRequired: false },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.workersView,
    managePermission: MANUFACTURING_PERMISSIONS.targetsManage,
    aggregateType: "production_standard",
    scope: "branch",
  },
  boms: {
    key: "boms",
    title: "BOMs",
    singularTitle: "BOM",
    description: "Bill of material headers for manufacturable products. No material consumption is posted.",
    basePath: `${basePath}/boms`,
    tableName: "manufacturing_boms",
    selectColumns: "id, tenant_id, company_id, branch_id, manufacturing_product_id, bom_key, version_key, inventory_quantity_owner, cost_calculation_owner, status, is_active, created_at, updated_at, version",
    searchColumns: ["bom_key", "version_key", "status"],
    columns: [
      { key: "bomKey", header: "BOM Code", field: "bomKey" },
      { key: "versionKey", header: "Version", field: "versionKey" },
      { key: "manufacturingProductId", header: "Product", field: "manufacturingProductId" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "BOM", scope: "company" }, name: "bomKey", label: "BOM Code", type: "text", isRequired: true },
      { autoCode: { prefix: "VER", scope: "company" }, name: "versionKey", label: "Version Code", type: "text", isRequired: true },
      { name: "manufacturingProductId", label: "Manufacturing product", type: "text", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.bomView,
    managePermission: MANUFACTURING_PERMISSIONS.bomManage,
    createdEventName: "manufacturing.bom.created",
    aggregateType: "manufacturing_bom",
    scope: "company",
  },
  "routing-plans": {
    key: "routing-plans",
    title: "Routing Plans",
    singularTitle: "Routing Plan",
    description: "Manufacturing engineering routing headers. No execution runtime is implemented.",
    basePath: `${basePath}/routing-plans`,
    tableName: "manufacturing_routings",
    selectColumns: "id, tenant_id, company_id, branch_id, manufacturing_product_id, routing_key, version_key, status, is_active, created_at, updated_at, version",
    searchColumns: ["routing_key", "version_key", "status"],
    columns: [
      { key: "routingKey", header: "Routing Code", field: "routingKey" },
      { key: "versionKey", header: "Version", field: "versionKey" },
      { key: "manufacturingProductId", header: "Product", field: "manufacturingProductId" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "RTG", scope: "company" }, name: "routingKey", label: "Routing Code", type: "text", isRequired: true },
      { autoCode: { prefix: "VER", scope: "company" }, name: "versionKey", label: "Version Code", type: "text", isRequired: true },
      { name: "manufacturingProductId", label: "Manufacturing product", type: "text", isRequired: true },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.routingView,
    managePermission: MANUFACTURING_PERMISSIONS.routingManage,
    createdEventName: "manufacturing.routing.created",
    aggregateType: "manufacturing_routing",
    scope: "company",
  },
  "production-plans": {
    key: "production-plans",
    title: "Production Plans",
    singularTitle: "Production Plan",
    description: "Branch-scoped production plans without a scheduling engine.",
    basePath: `${basePath}/production-plans`,
    tableName: "manufacturing_plans",
    selectColumns: "id, tenant_id, company_id, branch_id, plan_key, plan_date, scheduling_engine_implemented, status, is_active, created_at, updated_at, version",
    searchColumns: ["plan_key", "status"],
    columns: [
      { key: "planKey", header: "Plan Code", field: "planKey" },
      { key: "planDate", header: "Date", field: "planDate" },
      { key: "status", header: "Status", field: "status" },
      { key: "isActive", header: "Active", field: "isActive" },
    ],
    formFields: [
      { autoCode: { prefix: "PLAN", scope: "branch" }, name: "planKey", label: "Plan Code", type: "text", isRequired: true },
      { name: "planDate", label: "Plan date", type: "date", isRequired: true },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.planningView,
    managePermission: MANUFACTURING_PERMISSIONS.planningManage,
    aggregateType: "manufacturing_plan",
    scope: "branch",
  },
  "manufacturing-orders": {
    key: "manufacturing-orders",
    title: "Manufacturing Orders",
    singularTitle: "Manufacturing Order",
    description: "Manufacturing order facts without execution runtime, costing, or inventory posting.",
    basePath: `${basePath}/manufacturing-orders`,
    tableName: "manufacturing_orders",
    selectColumns: "id, tenant_id, company_id, branch_id, plan_line_id, manufacturing_product_id, order_key, planned_quantity, actual_quantity, execution_runtime_implemented, status, is_active, created_at, updated_at, version",
    searchColumns: ["order_key", "status"],
    columns: [
      { key: "orderKey", header: "Order Code", field: "orderKey" },
      { key: "manufacturingProductId", header: "Product", field: "manufacturingProductId" },
      { key: "plannedQuantity", header: "Planned", field: "plannedQuantity" },
      { key: "actualQuantity", header: "Actual", field: "actualQuantity" },
      { key: "status", header: "Status", field: "status" },
    ],
    formFields: [
      { autoCode: { prefix: "MO", scope: "branch" }, name: "orderKey", label: "Order Code", type: "text", isRequired: true },
      { name: "manufacturingProductId", label: "Manufacturing product", type: "text", isRequired: true },
      { name: "planLineId", label: "Plan line", type: "text", isRequired: false },
      { name: "plannedQuantity", label: "Planned quantity", type: "number", isRequired: true },
      { name: "actualQuantity", label: "Actual quantity", type: "number", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.executionView,
    managePermission: MANUFACTURING_PERMISSIONS.executionManage,
    aggregateType: "manufacturing_order",
    scope: "branch",
  },
  "work-orders": {
    key: "work-orders",
    title: "Work Orders",
    singularTitle: "Work Order",
    description: "Work order facts for operations without runtime execution or inventory posting.",
    basePath: `${basePath}/work-orders`,
    tableName: "manufacturing_work_orders",
    selectColumns: "id, tenant_id, company_id, branch_id, manufacturing_order_id, operation_id, work_order_key, planned_quantity, actual_quantity, execution_runtime_implemented, status, is_active, created_at, updated_at, version",
    searchColumns: ["work_order_key", "status"],
    columns: [
      { key: "workOrderKey", header: "Work Order", field: "workOrderKey" },
      { key: "manufacturingOrderId", header: "Manufacturing Order", field: "manufacturingOrderId" },
      { key: "operationId", header: "Operation", field: "operationId" },
      { key: "plannedQuantity", header: "Planned", field: "plannedQuantity" },
      { key: "actualQuantity", header: "Actual", field: "actualQuantity" },
      { key: "status", header: "Status", field: "status" },
    ],
    formFields: [
      { autoCode: { prefix: "WO", scope: "branch" }, name: "workOrderKey", label: "Work Order Code", type: "text", isRequired: true },
      { name: "manufacturingOrderId", label: "Manufacturing order", type: "text", isRequired: true },
      { name: "operationId", label: "Operation", type: "text", isRequired: false },
      { name: "plannedQuantity", label: "Planned quantity", type: "number", isRequired: true },
      { name: "actualQuantity", label: "Actual quantity", type: "number", isRequired: false },
      { name: "status", label: "Status", type: "text", isRequired: true },
      { name: "isActive", label: "Active", type: "checkbox", isRequired: false },
    ],
    readPermission: MANUFACTURING_PERMISSIONS.executionView,
    managePermission: MANUFACTURING_PERMISSIONS.executionManage,
    aggregateType: "manufacturing_work_order",
    scope: "branch",
  },
} satisfies Record<ManufacturingResourceKey, ManufacturingResourceDefinition>;

export const MANUFACTURING_RESOURCE_LIST = Object.values(MANUFACTURING_RESOURCE_DEFINITIONS);

export function parseManufacturingResourceKey(value: string): ManufacturingResourceKey {
  if (value in MANUFACTURING_RESOURCE_DEFINITIONS) return value as ManufacturingResourceKey;
  throw new Error(`Unsupported manufacturing resource: ${value}`);
}

export function getManufacturingResourceDefinition(key: ManufacturingResourceKey) {
  return MANUFACTURING_RESOURCE_DEFINITIONS[key];
}
