export type InventoryProductStatus = "draft" | "active" | "inactive" | "locked" | "archived";
export type InventoryProductKind = "stockable" | "consumable" | "service" | "asset" | "rental" | "kit";
export type InventoryTrackingMode = "none" | "lot" | "serial";
export type InventoryReservationPolicy = "none" | "soft" | "hard";
export type InventoryOnlineStatus = "draft" | "ready" | "published" | "hidden" | "archived";

export type InventoryProductListQuery = Readonly<{
  categoryId?: string;
  cursor?: string | null;
  hasLotTracking?: boolean;
  hasSerialTracking?: boolean;
  hasVariants?: boolean;
  onlineStatus?: InventoryOnlineStatus;
  pageSize: number;
  productKind?: InventoryProductKind;
  search?: string;
  sellable?: boolean;
  status?: InventoryProductStatus;
  stockable?: boolean;
  purchasable?: boolean;
  trackingMode?: InventoryTrackingMode;
}>;

export type InventoryProductRecord = Readonly<{
  id: string;
  tenantId: string;
  companyId: string;
  branchId: string | null;
  productCategoryId: string | null;
  categoryId: string | null;
  subcategoryId: string | null;
  baseUomId: string;
  purchaseUomId: string | null;
  salesUomId: string | null;
  defaultWarehouseId: string | null;
  defaultLocationId: string | null;
  productKey: string;
  sku: string;
  barcode: string | null;
  name: string;
  nameAr: string | null;
  shortName: string | null;
  description: string | null;
  internalNotes: string | null;
  productKind: InventoryProductKind;
  trackingMode: InventoryTrackingMode;
  reservationPolicy: InventoryReservationPolicy;
  brand: string | null;
  supplierPartyId: string | null;
  sectionKey: string | null;
  productTypeKey: string | null;
  openingBalanceQty: number;
  minimumStockQty: number;
  maximumStockQty: number | null;
  reorderPointQty: number | null;
  weight: number | null;
  length: number | null;
  width: number | null;
  height: number | null;
  volume: number | null;
  countryOfOrigin: string | null;
  hsCode: string | null;
  shippingClass: string | null;
  purchasePrice: number;
  retailPrice: number;
  wholesalePrice: number;
  onlinePrice: number;
  discountAllowed: boolean;
  commissionRate: number;
  priceIncludesTax: boolean;
  taxDefinitionId: string | null;
  currencyId: string | null;
  onlineEnabled: boolean;
  onlineStatus: InventoryOnlineStatus;
  onlineSlug: string | null;
  onlineTitle: string | null;
  onlineShortDescription: string | null;
  onlineLongDescription: string | null;
  onlineFeatures: readonly string[];
  onlineSpecifications: Record<string, string>;
  onlinePackageContents: readonly string[];
  seoTitle: string | null;
  seoDescription: string | null;
  seoKeywords: readonly string[];
  ogImageUrl: string | null;
  canonicalUrl: string | null;
  isFeatured: boolean;
  isNewArrival: boolean;
  isBestSeller: boolean;
  allowReviews: boolean;
  allowRatings: boolean;
  coverImageUrl: string | null;
  galleryUrls: readonly string[];
  videoUrls: readonly string[];
  manualUrls: readonly string[];
  isStockable: boolean;
  isSellable: boolean;
  isPurchasable: boolean;
  isManufacturable: boolean;
  isService: boolean;
  hasVariants: boolean;
  hasSerialTracking: boolean;
  hasLotTracking: boolean;
  isDiscountable: boolean;
  isOnlineVisible: boolean;
  categoryLabel: string | null;
  subcategoryLabel: string | null;
  baseUomLabel: string | null;
  supplierLabel: string | null;
  currencyLabel: string | null;
  taxDefinitionLabel: string | null;
  costObjectKey: string | null;
  financeDimensionKey: string | null;
  status: InventoryProductStatus;
  isActive: boolean;
  createdAt: string;
  createdBy: string | null;
  updatedAt: string;
  updatedBy: string | null;
  archivedAt: string | null;
  archivedBy: string | null;
  version: number;
}>;

export type InventoryProductUnitMapping = Readonly<{
  uomId: string;
  conversionFactor: number;
  barcode?: string | null;
  isBase?: boolean;
  isPurchaseDefault?: boolean;
  isSalesDefault?: boolean;
  isOnlineDefault?: boolean;
}>;

export type InventoryProductPriceMapping = Readonly<{
  priceType: "purchase" | "retail" | "wholesale" | "online" | "distributor" | "custom";
  currencyId?: string | null;
  price: number;
}>;

export type InventoryProductMediaMapping = Readonly<{
  mediaType: "image" | "video" | "manual" | "certificate" | "attachment";
  url: string;
  title?: string | null;
  altText?: string | null;
  sortOrder?: number;
  isCover?: boolean;
}>;

export type InventoryProductLookup = Readonly<{
  id: string;
  label: string;
  meta?: string;
}>;

export type InventoryProductWorkspaceData = Readonly<{
  records: readonly InventoryProductRecord[];
  nextCursor: string | null;
  pageSize: number;
  branches: readonly InventoryProductLookup[];
  categories: readonly InventoryProductLookup[];
  subcategories: readonly InventoryProductLookup[];
  currencies: readonly InventoryProductLookup[];
  locations: readonly InventoryProductLookup[];
  suppliers: readonly InventoryProductLookup[];
  taxDefinitions: readonly InventoryProductLookup[];
  uoms: readonly InventoryProductLookup[];
  warehouses: readonly InventoryProductLookup[];
}>;
