import { definePermissionKey } from "@/platform/permissions/public-api";

export const MANUFACTURING_PERMISSIONS = {
  approvalsView: definePermissionKey("manufacturing.approvals.view"),
  assignmentsManage: definePermissionKey("manufacturing.assignments.manage"),
  auditView: definePermissionKey("manufacturing.audit.view"),
  bomManage: definePermissionKey("manufacturing.bom.manage"),
  bomView: definePermissionKey("manufacturing.bom.view"),
  costIntegrationView: definePermissionKey("manufacturing.cost-integration.view"),
  dailyReportsManage: definePermissionKey("manufacturing.daily-reports.manage"),
  dailyReportsView: definePermissionKey("manufacturing.daily-reports.view"),
  executionManage: definePermissionKey("manufacturing.execution.manage"),
  executionView: definePermissionKey("manufacturing.execution.view"),
  financeIntegrationView: definePermissionKey("manufacturing.finance-integration.view"),
  hrPayrollIntegrationView: definePermissionKey("manufacturing.hr-payroll-integration.view"),
  importExportManage: definePermissionKey("manufacturing.import-export.manage"),
  inventoryIntegrationView: definePermissionKey("manufacturing.inventory-integration.view"),
  kpisView: definePermissionKey("manufacturing.kpis.view"),
  linesManage: definePermissionKey("manufacturing.lines.manage"),
  linesView: definePermissionKey("manufacturing.lines.view"),
  machinesManage: definePermissionKey("manufacturing.machines.manage"),
  machinesView: definePermissionKey("manufacturing.machines.view"),
  manage: definePermissionKey("manufacturing.manage"),
  notificationsView: definePermissionKey("manufacturing.notifications.view"),
  operationsManage: definePermissionKey("manufacturing.operations.manage"),
  operationsView: definePermissionKey("manufacturing.operations.view"),
  planningManage: definePermissionKey("manufacturing.planning.manage"),
  planningView: definePermissionKey("manufacturing.planning.view"),
  qualityReadinessView: definePermissionKey("manufacturing.quality-readiness.view"),
  routingManage: definePermissionKey("manufacturing.routing.manage"),
  routingView: definePermissionKey("manufacturing.routing.view"),
  searchView: definePermissionKey("manufacturing.search.view"),
  targetsManage: definePermissionKey("manufacturing.targets.manage"),
  targetsView: definePermissionKey("manufacturing.targets.view"),
  view: definePermissionKey("manufacturing.view"),
  workCentersManage: definePermissionKey("manufacturing.work-centers.manage"),
  workCentersView: definePermissionKey("manufacturing.work-centers.view"),
  legacyWorkCentersManage: definePermissionKey("manufacturing.work_centers.manage"),
  legacyWorkCentersView: definePermissionKey("manufacturing.work_centers.view"),
  workstationsManage: definePermissionKey("manufacturing.workstations.manage"),
  workstationsView: definePermissionKey("manufacturing.workstations.view"),
  workersManage: definePermissionKey("manufacturing.workers.manage"),
  workersView: definePermissionKey("manufacturing.workers.view"),
  workflowReadinessView: definePermissionKey("manufacturing.workflow-readiness.view"),
} as const;

export const MANUFACTURING_PERMISSION_LIST = Object.values(MANUFACTURING_PERMISSIONS);
