import { FINANCE_PERMISSIONS } from "../permissions/permission-registry";
import type { FinanceEntityDescriptor, FinanceEntityKey } from "./types";

const RECORD_STATUS_VALUES = ["draft", "active", "inactive", "locked", "archived"] as const;
const PERIOD_STATUS_VALUES = ["draft", "active", "locked", "archived"] as const;

export const FINANCE_ENTITIES: Readonly<Record<FinanceEntityKey, FinanceEntityDescriptor>> = {
  "account-types": {
    key: "account-types",
    table: "finance_account_types",
    title: "Account Types",
    singular: "Account Type",
    description: "Classify chart of accounts by account class and normal balance.",
    basePath: "/erp/finance/account-types",
    icon: "layers",
    viewPermission: FINANCE_PERMISSIONS.accountsView,
    managePermission: FINANCE_PERMISSIONS.accountsManage,
    searchColumns: ["account_type_key", "name"],
    statusField: "is_active",
    fields: [
      { autoCode: { prefix: "AT", scope: "company" }, name: "accountTypeKey", column: "account_type_key", label: "Account Type Code", type: "text", required: true, transform: "lower", showInList: true, helpText: "Generated unique code within the company." },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      {
        name: "accountClass",
        column: "account_class",
        label: "Account class",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "asset", label: "Asset" },
          { value: "liability", label: "Liability" },
          { value: "equity", label: "Equity" },
          { value: "revenue", label: "Revenue" },
          { value: "expense", label: "Expense" },
          { value: "contra_asset", label: "Contra asset" },
          { value: "contra_liability", label: "Contra liability" },
          { value: "statistical", label: "Statistical" },
        ],
      },
      {
        name: "normalBalance",
        column: "normal_balance",
        label: "Normal balance",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "debit", label: "Debit" },
          { value: "credit", label: "Credit" },
          { value: "none", label: "None" },
        ],
      },
      { name: "description", column: "description", label: "Description", type: "textarea" },
    ],
  },
  "chart-of-accounts": {
    key: "chart-of-accounts",
    table: "finance_accounts",
    title: "Chart of Accounts",
    singular: "Account",
    description: "Hierarchical account definitions. Foundation only: no journal entries or ledger posting.",
    basePath: "/erp/finance/chart-of-accounts",
    icon: "list-tree",
    viewPermission: FINANCE_PERMISSIONS.accountsView,
    managePermission: FINANCE_PERMISSIONS.accountsManage,
    searchColumns: ["account_code", "name"],
    statusField: "is_active",
    supportsTree: true,
    treeParentField: "parentAccountId",
    reconciliationNotes: ["RI-01: GL posting and journal entries are not part of the accepted Finance Foundation."],
    relations: [
      { key: "accountType", label: "Account type", field: "accountTypeId", targetBasePath: "/erp/finance/account-types" },
      { key: "parentAccount", label: "Parent account", field: "parentAccountId", targetBasePath: "/erp/finance/chart-of-accounts" },
    ],
    fields: [
      { autoCode: { prefix: "ACC", scope: "company", storageCase: "upper" }, name: "accountCode", column: "account_code", label: "Account Code", type: "text", required: true, transform: "upper", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "accountTypeId", column: "account_type_id", label: "Account type", type: "text", required: true, showInList: true, helpText: "Account type definition identifier." },
      { name: "parentAccountId", column: "parent_account_id", label: "Parent account", type: "text", helpText: "Optional parent account for hierarchy." },
      { name: "currencyCode", column: "currency_code", label: "Currency", type: "text", transform: "upper", showInList: true },
      { name: "costCenterRequired", column: "cost_center_required", label: "Cost center required", type: "checkbox", showInList: true },
      { name: "dimensionRequirements", column: "dimension_requirements", label: "Dimension requirements", type: "tags", helpText: "Comma separated dimension keys required for future posting." },
      { name: "description", column: "description", label: "Description", type: "textarea" },
    ],
  },
  journals: {
    key: "journals",
    table: "finance_journals",
    title: "Journals",
    singular: "Journal",
    description: "Journal definitions. Posting stays disabled in the foundation.",
    basePath: "/erp/finance/journals",
    icon: "book",
    viewPermission: FINANCE_PERMISSIONS.journalsView,
    managePermission: FINANCE_PERMISSIONS.journalsManage,
    searchColumns: ["journal_key", "name"],
    statusField: "is_active",
    reconciliationNotes: ["RI-01: Journal entry posting is intentionally disabled (posting_enabled = false)."],
    fields: [
      { autoCode: { prefix: "JRN", scope: "company" }, name: "journalKey", column: "journal_key", label: "Journal Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      {
        name: "journalKind",
        column: "journal_kind",
        label: "Journal kind",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "general", label: "General" },
          { value: "sales", label: "Sales" },
          { value: "purchase", label: "Purchase" },
          { value: "cash", label: "Cash" },
          { value: "bank", label: "Bank" },
          { value: "inventory", label: "Inventory" },
          { value: "payroll", label: "Payroll" },
          { value: "adjustment", label: "Adjustment" },
        ],
      },
      { name: "defaultCurrencyCode", column: "default_currency_code", label: "Default currency", type: "text", transform: "upper" },
      { name: "requiresApproval", column: "requires_approval", label: "Requires approval", type: "checkbox", showInList: true },
      { name: "description", column: "description", label: "Description", type: "textarea" },
    ],
  },
  "fiscal-years": {
    key: "fiscal-years",
    table: "finance_fiscal_years",
    title: "Fiscal Years",
    singular: "Fiscal Year",
    description: "Define fiscal year calendars and their lock status.",
    basePath: "/erp/finance/fiscal-years",
    icon: "calendar-range",
    viewPermission: FINANCE_PERMISSIONS.fiscalPeriodsView,
    managePermission: FINANCE_PERMISSIONS.fiscalPeriodsManage,
    searchColumns: ["fiscal_year_key", "name"],
    statusField: "status",
    statusValues: PERIOD_STATUS_VALUES,
    defaultStatus: "draft",
    fields: [
      { autoCode: { prefix: "FY", scope: "company" }, name: "fiscalYearKey", column: "fiscal_year_key", label: "Fiscal Year Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "startsOn", column: "starts_on", label: "Starts on", type: "date", required: true, showInList: true },
      { name: "endsOn", column: "ends_on", label: "Ends on", type: "date", required: true, showInList: true },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        showInList: true,
        options: PERIOD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  "fiscal-periods": {
    key: "fiscal-periods",
    table: "finance_fiscal_periods",
    title: "Fiscal Periods",
    singular: "Fiscal Period",
    description: "Periods inside a fiscal year, including opening, regular, adjustment, and closing periods.",
    basePath: "/erp/finance/fiscal-periods",
    icon: "calendar-days",
    viewPermission: FINANCE_PERMISSIONS.fiscalPeriodsView,
    managePermission: FINANCE_PERMISSIONS.fiscalPeriodsManage,
    searchColumns: ["fiscal_period_key", "name"],
    statusField: "status",
    statusValues: PERIOD_STATUS_VALUES,
    defaultStatus: "draft",
    relations: [
      { key: "fiscalYear", label: "Fiscal year", field: "fiscalYearId", targetBasePath: "/erp/finance/fiscal-years" },
    ],
    fields: [
      { name: "fiscalYearId", column: "fiscal_year_id", label: "Fiscal year", type: "text", required: true, showInList: true, helpText: "Parent fiscal year identifier." },
      { autoCode: { prefix: "FP", scope: "company" }, name: "fiscalPeriodKey", column: "fiscal_period_key", label: "Period Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "startsOn", column: "starts_on", label: "Starts on", type: "date", required: true, showInList: true },
      { name: "endsOn", column: "ends_on", label: "Ends on", type: "date", required: true, showInList: true },
      {
        name: "periodKind",
        column: "period_kind",
        label: "Period kind",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "opening", label: "Opening" },
          { value: "regular", label: "Regular" },
          { value: "adjustment", label: "Adjustment" },
          { value: "closing", label: "Closing" },
        ],
      },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        showInList: true,
        options: PERIOD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  currencies: {
    key: "currencies",
    table: "finance_currencies",
    title: "Currencies",
    singular: "Currency",
    description: "Company currency enablement and base currency selection.",
    basePath: "/erp/finance/currencies",
    icon: "coins",
    viewPermission: FINANCE_PERMISSIONS.currenciesView,
    managePermission: FINANCE_PERMISSIONS.currenciesManage,
    searchColumns: ["currency_code", "name"],
    statusField: "status",
    statusValues: RECORD_STATUS_VALUES,
    defaultStatus: "active",
    fields: [
      { name: "currencyCode", column: "currency_code", label: "Currency code", type: "text", required: true, transform: "upper", showInList: true, helpText: "ISO 4217 three letter code." },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "symbol", column: "symbol", label: "Symbol", type: "text", showInList: true },
      { name: "precision", column: "precision", label: "Precision", type: "number", required: true, min: 0, max: 6, showInList: true },
      { name: "isBaseCurrency", column: "is_base_currency", label: "Base currency", type: "checkbox", showInList: true },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        options: RECORD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  taxes: {
    key: "taxes",
    table: "finance_tax_definitions",
    title: "Taxes",
    singular: "Tax Definition",
    description: "Tax definition records. Calculation stays disabled in the foundation.",
    basePath: "/erp/finance/taxes",
    icon: "percent",
    viewPermission: FINANCE_PERMISSIONS.taxDefinitionsView,
    managePermission: FINANCE_PERMISSIONS.taxDefinitionsManage,
    searchColumns: ["tax_key", "name"],
    statusField: "status",
    statusValues: RECORD_STATUS_VALUES,
    defaultStatus: "active",
    reconciliationNotes: [
      "RI-04: Tax definitions, financial tax tables, and tax-profiles must be reconciled.",
      "Calculation is disabled (calculation_supported = false).",
    ],
    fields: [
      { autoCode: { prefix: "TAX", scope: "company" }, name: "taxKey", column: "tax_key", label: "Tax Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      {
        name: "calculationMode",
        column: "calculation_mode",
        label: "Calculation mode",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "inclusive", label: "Inclusive" },
          { value: "exclusive", label: "Exclusive" },
        ],
      },
      { name: "rate", column: "rate", label: "Rate (0-1)", type: "number", step: "0.000001", min: 0, max: 1, showInList: true, helpText: "Stored as a fraction, e.g. 0.15 for 15%." },
      { name: "isRecoverable", column: "is_recoverable", label: "Recoverable", type: "checkbox" },
      { name: "isWithholding", column: "is_withholding", label: "Withholding", type: "checkbox" },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        options: RECORD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  "payment-terms": {
    key: "payment-terms",
    table: "finance_payment_terms",
    title: "Payment Terms",
    singular: "Payment Term",
    description: "Payment term definitions. Payment execution stays disabled in the foundation.",
    basePath: "/erp/finance/payment-terms",
    icon: "wallet",
    viewPermission: FINANCE_PERMISSIONS.paymentTermsView,
    managePermission: FINANCE_PERMISSIONS.paymentTermsManage,
    searchColumns: ["terms_key", "name"],
    statusField: "status",
    statusValues: RECORD_STATUS_VALUES,
    defaultStatus: "active",
    fields: [
      { autoCode: { prefix: "TERM", scope: "company" }, name: "termsKey", column: "terms_key", label: "Terms Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { name: "dueDays", column: "due_days", label: "Due days", type: "number", required: true, min: 0, showInList: true },
      { name: "discountDays", column: "discount_days", label: "Discount days", type: "number", min: 0, helpText: "Must be less than or equal to due days." },
      { name: "discountPercent", column: "discount_percent", label: "Discount percent (0-1)", type: "number", step: "0.000001", min: 0, max: 1 },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        options: RECORD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  "cost-centers": {
    key: "cost-centers",
    table: "finance_dimensions",
    title: "Cost Centers",
    singular: "Cost Center",
    description: "Cost center dimensions used for accounting analysis and future posting requirements.",
    basePath: "/erp/finance/cost-centers",
    icon: "target",
    viewPermission: FINANCE_PERMISSIONS.dimensionsView,
    managePermission: FINANCE_PERMISSIONS.dimensionsManage,
    searchColumns: ["dimension_key", "name", "cost_center_key"],
    statusField: "status",
    statusValues: RECORD_STATUS_VALUES,
    defaultStatus: "active",
    fixedFilter: { column: "dimension_kind", value: "cost_center" },
    fields: [
      { autoCode: { prefix: "CC", scope: "company" }, name: "dimensionKey", column: "dimension_key", label: "Cost Center Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      { autoCode: { prefix: "CCREF", scope: "company" }, name: "costCenterKey", column: "cost_center_key", label: "Cost Center Reference Code", type: "text", transform: "lower", showInList: true },
      { name: "requiredForPosting", column: "required_for_posting", label: "Required for posting", type: "checkbox", showInList: true },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        options: RECORD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
  dimensions: {
    key: "dimensions",
    table: "finance_dimensions",
    title: "Financial Dimensions",
    singular: "Dimension",
    description: "Accounting dimensions for analytical reporting and posting requirements.",
    basePath: "/erp/finance/dimensions",
    icon: "shapes",
    viewPermission: FINANCE_PERMISSIONS.dimensionsView,
    managePermission: FINANCE_PERMISSIONS.dimensionsManage,
    searchColumns: ["dimension_key", "name"],
    statusField: "status",
    statusValues: RECORD_STATUS_VALUES,
    defaultStatus: "active",
    fields: [
      { autoCode: { prefix: "DIM", scope: "company" }, name: "dimensionKey", column: "dimension_key", label: "Dimension Code", type: "text", required: true, transform: "lower", showInList: true },
      { name: "name", column: "name", label: "Name", type: "text", required: true, showInList: true },
      {
        name: "dimensionKind",
        column: "dimension_kind",
        label: "Dimension kind",
        type: "select",
        required: true,
        showInList: true,
        options: [
          { value: "company", label: "Company" },
          { value: "branch", label: "Branch" },
          { value: "department", label: "Department" },
          { value: "cost_center", label: "Cost center" },
          { value: "project", label: "Project" },
          { value: "warehouse", label: "Warehouse" },
          { value: "employee", label: "Employee" },
          { value: "customer", label: "Customer" },
          { value: "supplier", label: "Supplier" },
          { value: "product", label: "Product" },
          { value: "custom", label: "Custom" },
        ],
      },
      { autoCode: { prefix: "CCREF", scope: "company" }, name: "costCenterKey", column: "cost_center_key", label: "Cost Center Reference Code", type: "text", transform: "lower" },
      { name: "referenceEntityType", column: "reference_entity_type", label: "Reference entity type", type: "text", transform: "lower" },
      { name: "requiredForPosting", column: "required_for_posting", label: "Required for posting", type: "checkbox", showInList: true },
      {
        name: "status",
        column: "status",
        label: "Status",
        type: "select",
        required: true,
        options: RECORD_STATUS_VALUES.map((value) => ({ value, label: value })),
      },
    ],
  },
};

export const FINANCE_ENTITY_KEYS = Object.keys(FINANCE_ENTITIES) as FinanceEntityKey[];

export function getFinanceEntity(key: string): FinanceEntityDescriptor {
  const descriptor = FINANCE_ENTITIES[key as FinanceEntityKey];

  if (!descriptor) {
    throw new Error(`Unknown finance entity: ${key}`);
  }

  return descriptor;
}

export function isFinanceEntityKey(key: string): key is FinanceEntityKey {
  return key in FINANCE_ENTITIES;
}
