import { defineAppManifest, type AppManifest } from "@/platform/app-registry/public-api";

import { MANUFACTURING_PERMISSIONS } from "./permissions/permission-registry";

export const manufacturingAppManifest = defineAppManifest({
  capabilities: [
    { key: "manufacturing.navigation", requiredPermission: MANUFACTURING_PERMISSIONS.view, type: "navigation" },
    { key: "manufacturing.search", requiredPermission: MANUFACTURING_PERMISSIONS.searchView, type: "search" },
    { key: "manufacturing.reports", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "report" },
    { key: "manufacturing.prints", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "print" },
    { key: "manufacturing.dashboards", requiredPermission: MANUFACTURING_PERMISSIONS.kpisView, type: "dashboard" },
    { key: "manufacturing.document-contracts", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "workflow" },
    { key: "manufacturing.approval-readiness", requiredPermission: MANUFACTURING_PERMISSIONS.reportsApprove, type: "approval" },
    { key: "manufacturing.import-export", requiredPermission: MANUFACTURING_PERMISSIONS.importExportManage, type: "connector" },
    { key: "manufacturing.notifications", requiredPermission: MANUFACTURING_PERMISSIONS.notificationsView, type: "notification" },
    { key: "manufacturing.production-plans.contract", requiredPermission: MANUFACTURING_PERMISSIONS.planningView, type: "route" },
    { key: "manufacturing.orders.contract", requiredPermission: MANUFACTURING_PERMISSIONS.ordersView, type: "route" },
    { key: "manufacturing.operations.contract", requiredPermission: MANUFACTURING_PERMISSIONS.operationsView, type: "route" },
    { key: "manufacturing.crew.contract", requiredPermission: MANUFACTURING_PERMISSIONS.crewView, type: "route" },
    { key: "manufacturing.production-reports.contract", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "route" },
  ],
  category: "operations",
  commands: [
    {
      actionType: "open-page",
      appKey: "manufacturing",
      category: "navigation",
      href: "/erp/manufacturing/contracts",
      key: "manufacturing.contracts.open",
      label: "Open Manufacturing Contract Registry",
      order: 40,
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
      scope: "global",
      supportedExperiences: ["erp"],
    },
    {
      actionType: "open-page",
      appKey: "manufacturing",
      category: "navigation",
      href: "/erp/manufacturing/contracts/production-reports",
      key: "manufacturing.production-reports.contract.open",
      label: "Open Production Report Contract",
      order: 42,
      requiredPermission: MANUFACTURING_PERMISSIONS.reportsView,
      scope: "global",
      supportedExperiences: ["erp"],
    },
    {
      actionType: "open-page",
      appKey: "manufacturing",
      category: "navigation",
      href: "/erp/manufacturing/documentation",
      key: "manufacturing.documentation.open",
      label: "Open Manufacturing Documentation",
      order: 41,
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
      scope: "global",
      supportedExperiences: ["erp"],
    },
  ],
  dashboards: [
    { key: "manufacturing.foundation.dashboard-template", requiredPermission: MANUFACTURING_PERMISSIONS.kpisView, type: "dashboard" },
  ],
  dependencies: [
    { appKey: "platform", reason: "Relies on Platform v1.0 app registry, security, data/RLS, document, event, workflow, approval, notification, search, import/export, report, print, dashboard, job, and cost contracts." },
    { appKey: "finance", reason: "Uses accepted Finance Foundation posting-readiness contracts only; no finance logic is implemented." },
    { appKey: "inventory", reason: "Uses accepted Inventory Foundation movement contracts only; Inventory remains stock quantity owner." },
  ],
  description: "Foundation-only Manufacturing app for production master data, plans, targets, daily reports, execution contracts, KPI facts, and integration readiness.",
  experiences: ["erp"],
  featureFlags: [],
  icon: "factory",
  key: "manufacturing",
  name: "Manufacturing Foundation",
  navigation: [
    {
      appKey: "manufacturing",
      href: "/erp/manufacturing",
      key: "manufacturing.launcher",
      kind: "app",
      label: "Manufacturing",
      order: 40,
      placement: "app-launcher",
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
      supportedExperiences: ["erp"],
    },
    {
      appKey: "manufacturing",
      href: "/erp/manufacturing",
      key: "manufacturing.sidebar",
      label: "Manufacturing Foundation",
      order: 40,
      placement: "contextual-sidebar",
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
      supportedExperiences: ["erp"],
    },
  ],
  permissions: [
    MANUFACTURING_PERMISSIONS.view,
    MANUFACTURING_PERMISSIONS.planningView,
    MANUFACTURING_PERMISSIONS.planningManage,
    MANUFACTURING_PERMISSIONS.ordersView,
    MANUFACTURING_PERMISSIONS.ordersManage,
    MANUFACTURING_PERMISSIONS.ordersRelease,
    MANUFACTURING_PERMISSIONS.ordersClose,
    MANUFACTURING_PERMISSIONS.operationsView,
    MANUFACTURING_PERMISSIONS.operationsManage,
    MANUFACTURING_PERMISSIONS.crewView,
    MANUFACTURING_PERMISSIONS.crewManage,
    MANUFACTURING_PERMISSIONS.crewApprove,
    MANUFACTURING_PERMISSIONS.reportsView,
    MANUFACTURING_PERMISSIONS.reportsCreate,
    MANUFACTURING_PERMISSIONS.reportsSubmit,
    MANUFACTURING_PERMISSIONS.reportsApprove,
    MANUFACTURING_PERMISSIONS.reportsPost,
    MANUFACTURING_PERMISSIONS.scrapManage,
    MANUFACTURING_PERMISSIONS.downtimeManage,
    MANUFACTURING_PERMISSIONS.reworkManage,
    MANUFACTURING_PERMISSIONS.kpisView,
  ],
  prints: [
    { key: "manufacturing.foundation.daily-production-print", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "print" },
  ],
  quickActions: [],
  reports: [
    { key: "manufacturing.foundation.readiness", requiredPermission: MANUFACTURING_PERMISSIONS.reportsView, type: "report" },
  ],
  notifications: [
    { key: "manufacturing.foundation.notification-readiness", requiredPermission: MANUFACTURING_PERMISSIONS.notificationsView, type: "notification" },
  ],
  routes: [
    {
      experience: "erp",
      key: "manufacturing.contracts",
      label: "Manufacturing Foundation",
      path: "/erp/manufacturing/contracts",
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
    },
    {
      experience: "erp",
      key: "manufacturing.production-plans.contract",
      label: "Production Plan Contract",
      path: "/erp/manufacturing/contracts/production-plans",
      requiredPermission: MANUFACTURING_PERMISSIONS.planningView,
    },
    {
      experience: "erp",
      key: "manufacturing.orders.contract",
      label: "Manufacturing Order Contract",
      path: "/erp/manufacturing/contracts/orders",
      requiredPermission: MANUFACTURING_PERMISSIONS.ordersView,
    },
    {
      experience: "erp",
      key: "manufacturing.operations.contract",
      label: "Operation Contract",
      path: "/erp/manufacturing/contracts/operations",
      requiredPermission: MANUFACTURING_PERMISSIONS.operationsView,
    },
    {
      experience: "erp",
      key: "manufacturing.crew.contract",
      label: "Crew Assignment Contract",
      path: "/erp/manufacturing/contracts/crew-assignments",
      requiredPermission: MANUFACTURING_PERMISSIONS.crewView,
    },
    {
      experience: "erp",
      key: "manufacturing.production-reports.contract",
      label: "Production Report Contract",
      path: "/erp/manufacturing/contracts/production-reports",
      requiredPermission: MANUFACTURING_PERMISSIONS.reportsView,
    },
    {
      experience: "erp",
      key: "manufacturing.documentation",
      label: "Manufacturing Documentation",
      path: "/erp/manufacturing/documentation",
      requiredPermission: MANUFACTURING_PERMISSIONS.view,
    },
  ],
  sensitiveData: "sensitive",
  settings: [
    { key: "manufacturing.foundation.settings", requiredPermission: MANUFACTURING_PERMISSIONS.manage, type: "setting" },
  ],
  statuses: ["draft", "active", "released", "completed", "cancelled", "inactive", "locked", "archived"],
  version: "1.0.0",
} satisfies AppManifest);
