import { defineAppManifest, type AppManifest } from "@/platform/app-registry/public-api";

import { HR_PERMISSIONS } from "./permissions/permission-registry";

export const hrAppManifest = defineAppManifest({
  capabilities: [
    { key: "hr.navigation", requiredPermission: HR_PERMISSIONS.view, type: "navigation" },
    { key: "hr.search", requiredPermission: HR_PERMISSIONS.searchView, type: "search" },
    { key: "hr.reports", requiredPermission: HR_PERMISSIONS.reportsView, type: "report" },
    { key: "hr.prints", requiredPermission: HR_PERMISSIONS.reportsView, type: "print" },
    { key: "hr.dashboards", requiredPermission: HR_PERMISSIONS.reportsView, type: "dashboard" },
    { key: "hr.import-export", requiredPermission: HR_PERMISSIONS.importExportManage, type: "connector" },
    { key: "hr.document-contracts", requiredPermission: HR_PERMISSIONS.contractsView, type: "workflow" },
    { key: "hr.timeline", requiredPermission: HR_PERMISSIONS.timelineView, type: "workflow" },
    { key: "hr.policy-foundation", requiredPermission: HR_PERMISSIONS.policiesView, type: "automation" },
    { key: "hr.policy-simulator-readiness", requiredPermission: HR_PERMISSIONS.policySimulatorView, type: "automation" },
    { key: "hr.compensation-foundation", requiredPermission: HR_PERMISSIONS.compensationView, type: "automation" },
    { key: "hr.salary-package-foundation", requiredPermission: HR_PERMISSIONS.salaryPackagesView, type: "automation" },
    { key: "hr.compensation-snapshot-readiness", requiredPermission: HR_PERMISSIONS.compensationView, type: "automation" },
    { key: "hr.workforce-foundation", requiredPermission: HR_PERMISSIONS.workforceView, type: "automation" },
    { key: "hr.shift-schedule-foundation", requiredPermission: HR_PERMISSIONS.shiftsView, type: "automation" },
    { key: "hr.workforce-planning-readiness", requiredPermission: HR_PERMISSIONS.workforceView, type: "automation" },
    { key: "hr.device-readiness", requiredPermission: HR_PERMISSIONS.devicesView, type: "automation" },
    { key: "hr.workforce-enterprise-hardening", requiredPermission: HR_PERMISSIONS.workforceMonitorView, type: "automation" },
    { key: "hr.attendance-foundation", requiredPermission: HR_PERMISSIONS.attendanceView, type: "automation" },
    { key: "hr.attendance-live-monitor", requiredPermission: HR_PERMISSIONS.attendanceMonitorView, type: "automation" },
    { key: "hr.attendance-review-readiness", requiredPermission: HR_PERMISSIONS.attendanceReview, type: "automation" },
    { key: "hr.attendance-payroll-snapshot-readiness", requiredPermission: HR_PERMISSIONS.attendanceView, type: "automation" },
    { key: "hr.architecture-refactor-gate", requiredPermission: HR_PERMISSIONS.view, type: "automation" },
    { key: "hr.leave-absence-foundation", requiredPermission: HR_PERMISSIONS.leaveView, type: "automation" },
    { key: "hr.payroll-foundation", requiredPermission: HR_PERMISSIONS.payrollView, type: "automation" },
    { key: "hr.payroll-relationship-foundation", requiredPermission: HR_PERMISSIONS.payrollRelationshipsView, type: "automation" },
    { key: "hr.payroll-runtime-foundation", requiredPermission: HR_PERMISSIONS.payrollRun, type: "automation" },
    { key: "hr.payroll-batch-foundation", requiredPermission: HR_PERMISSIONS.payrollBatchesView, type: "automation" },
    { key: "hr.payroll-snapshot-readiness", requiredPermission: HR_PERMISSIONS.payrollSnapshotsView, type: "automation" },
    { key: "hr.payroll-posting-readiness", requiredPermission: HR_PERMISSIONS.payrollPostingManage, type: "automation" },
    { key: "hr.payroll-retro-readiness", requiredPermission: HR_PERMISSIONS.payrollManage, type: "automation" },
    { key: "hr.payroll-final-settlement-readiness", requiredPermission: HR_PERMISSIONS.payrollRun, type: "automation" },
    { key: "hr.payroll-finance-readiness", requiredPermission: HR_PERMISSIONS.payrollManage, type: "automation" },
    { key: "hr.payroll-cost-readiness", requiredPermission: HR_PERMISSIONS.payrollView, type: "automation" },
    { key: "hr.payroll-inputs-runtime-foundation", requiredPermission: HR_PERMISSIONS.payrollInputsView, type: "automation" },
    { key: "hr.payroll-adjustments-runtime-foundation", requiredPermission: HR_PERMISSIONS.payrollAdjustmentsManage, type: "automation" },
    { key: "hr.payroll-inputs-lock-readiness", requiredPermission: HR_PERMISSIONS.payrollLocksManageRuntime, type: "automation" },
    { key: "hr.payroll-recalculation-readiness", requiredPermission: HR_PERMISSIONS.payrollRun, type: "automation" },
    { key: "hr.payroll-calculation-foundation", requiredPermission: HR_PERMISSIONS.payrollCalculate, type: "automation" },
    { key: "hr.payroll-calculation-trace-readiness", requiredPermission: HR_PERMISSIONS.payrollTraceView, type: "automation" },
    { key: "hr.payroll-validation-foundation", requiredPermission: HR_PERMISSIONS.payrollValidate, type: "automation" },
    { key: "hr.payroll-locking-foundation", requiredPermission: HR_PERMISSIONS.payrollLock, type: "automation" },
    { key: "hr.payroll-closing-foundation", requiredPermission: HR_PERMISSIONS.payrollClose, type: "automation" },
    { key: "hr.payroll-reopen-readiness", requiredPermission: HR_PERMISSIONS.payrollReopen, type: "automation" },
    { key: "hr.payroll-exception-management-readiness", requiredPermission: HR_PERMISSIONS.payrollExceptionManage, type: "automation" },
    { key: "hr.payslip-publishing-foundation", requiredPermission: HR_PERMISSIONS.payslipsPublish, type: "automation" },
    { key: "hr.payslip-unpublish-readiness", requiredPermission: HR_PERMISSIONS.payslipsUnpublish, type: "automation" },
    { key: "hr.employee-payroll-portal-foundation", requiredPermission: HR_PERMISSIONS.payslipsViewSelf, type: "automation" },
    { key: "hr.payslip-publishing-audit-readiness", requiredPermission: HR_PERMISSIONS.payslipsAuditView, type: "automation" },
    { key: "hr.payroll-localization-foundation", requiredPermission: HR_PERMISSIONS.payrollLocalizationView, type: "automation" },
    { key: "hr.payroll-localization-pack-readiness", requiredPermission: HR_PERMISSIONS.payrollLocalizationPacksManage, type: "automation" },
    { key: "hr.payroll-statutory-rule-readiness", requiredPermission: HR_PERMISSIONS.payrollStatutoryRulesManage, type: "automation" },
    { key: "hr.payroll-country-profile-readiness", requiredPermission: HR_PERMISSIONS.payrollCountryProfilesManage, type: "automation" },
    { key: "hr.payroll-finance-bank-readiness-foundation", requiredPermission: HR_PERMISSIONS.payrollFinanceReadinessView, type: "automation" },
    { key: "hr.payroll-posting-readiness-v2", requiredPermission: HR_PERMISSIONS.payrollFinanceReadinessManage, type: "automation" },
    { key: "hr.payroll-bank-readiness-foundation", requiredPermission: HR_PERMISSIONS.payrollBankReadinessManage, type: "automation" },
    { key: "hr.payroll-cost-allocation-readiness", requiredPermission: HR_PERMISSIONS.payrollCostAllocationManage, type: "automation" },
    { key: "hr.payroll-portal-security-readiness", requiredPermission: HR_PERMISSIONS.payrollPortalSecurityView, type: "automation" },
    { key: "hr.payslip-download-authorization-readiness", requiredPermission: HR_PERMISSIONS.payslipsDownloadAuthorize, type: "automation" },
    { key: "hr.payslip-access-revocation-readiness", requiredPermission: HR_PERMISSIONS.payslipsAccessRevoke, type: "automation" },
    { key: "hr.payroll-ess-readiness", requiredPermission: HR_PERMISSIONS.payrollEssReadinessView, type: "automation" },
    { key: "hr.payroll-mss-readiness", requiredPermission: HR_PERMISSIONS.payrollMssReadinessView, type: "automation" },
    { key: "hr.payroll-formula-foundation", requiredPermission: HR_PERMISSIONS.payrollView, type: "automation" },
    { key: "hr.payroll-proration-readiness", requiredPermission: HR_PERMISSIONS.payrollCalculate, type: "automation" },
    { key: "hr.action-foundation", requiredPermission: HR_PERMISSIONS.actionsView, type: "workflow" },
    { key: "hr.action-document-engine-readiness", requiredPermission: HR_PERMISSIONS.actionsView, type: "workflow" },
    { key: "hr.action-timeline-readiness", requiredPermission: HR_PERMISSIONS.timelineView, type: "workflow" },
    { key: "hr.action-apply-foundation", requiredPermission: HR_PERMISSIONS.actionsApplyView, type: "workflow" },
    { key: "hr.action-apply-dry-run-readiness", requiredPermission: HR_PERMISSIONS.actionsApplyDryRun, type: "workflow" },
    { key: "hr.action-apply-rollback-readiness", requiredPermission: HR_PERMISSIONS.actionsApplyRollback, type: "workflow" },
    { key: "hr.workflow-approval-binding-foundation", requiredPermission: HR_PERMISSIONS.actionsWorkflowView, type: "workflow" },
    { key: "hr.workflow-binding-readiness", requiredPermission: HR_PERMISSIONS.actionsWorkflowView, type: "workflow" },
    { key: "hr.approval-binding-readiness", requiredPermission: HR_PERMISSIONS.actionsApprovalView, type: "approval" },
    { key: "hr.approval-matrix-readiness", requiredPermission: HR_PERMISSIONS.actionsApprovalMatrixView, type: "approval" },
    { key: "hr.delegation-readiness", requiredPermission: HR_PERMISSIONS.actionsDelegationView, type: "approval" },
    { key: "hr.template-lifecycle-foundation", requiredPermission: HR_PERMISSIONS.templatesView, type: "automation" },
    { key: "hr.capability-pack-foundation", requiredPermission: HR_PERMISSIONS.capabilityPacksView, type: "automation" },
    { key: "hr.lifecycle-template-foundation", requiredPermission: HR_PERMISSIONS.lifecycleTemplatesView, type: "automation" },
    { key: "hr.checklist-template-foundation", requiredPermission: HR_PERMISSIONS.checklistsView, type: "automation" },
    { key: "hr.assignment-foundation", requiredPermission: HR_PERMISSIONS.assignmentsView, type: "automation" },
    { key: "hr.assignment-resolution-readiness", requiredPermission: HR_PERMISSIONS.assignmentResolutionView, type: "automation" },
    { key: "hr.job-architecture-foundation", requiredPermission: HR_PERMISSIONS.jobsView, type: "automation" },
    { key: "hr.job-career-path-readiness", requiredPermission: HR_PERMISSIONS.jobsView, type: "automation" },
    { key: "hr.skills-competency-foundation", requiredPermission: HR_PERMISSIONS.skillsView, type: "automation" },
    { key: "hr.skill-gap-readiness", requiredPermission: HR_PERMISSIONS.skillsView, type: "automation" },
    { key: "hr.training-readiness", requiredPermission: HR_PERMISSIONS.skillsView, type: "automation" },
    { key: "hr.recruitment-readiness", requiredPermission: HR_PERMISSIONS.skillsView, type: "automation" },
    { key: "hr.workforce-planning-foundation", requiredPermission: HR_PERMISSIONS.workforceView, type: "automation" },
    { key: "hr.workforce-forecast-readiness", requiredPermission: HR_PERMISSIONS.workforceView, type: "automation" },
    { key: "hr.workforce-budget-readiness", requiredPermission: HR_PERMISSIONS.workforceView, type: "automation" },
    { key: "hr.notifications", requiredPermission: HR_PERMISSIONS.view, type: "notification" },
  ],
  category: "hr",
  commands: [
    {
      actionType: "open-page",
      appKey: "hr",
      category: "navigation",
      href: "/erp/hr",
      key: "hr.open",
      label: "Open HR Core Foundation",
      order: 50,
      requiredPermission: HR_PERMISSIONS.view,
      scope: "global",
      supportedExperiences: ["erp"],
    },
  ],
  dashboards: [
    { key: "hr.foundation.dashboard-template", requiredPermission: HR_PERMISSIONS.reportsView, type: "dashboard" },
  ],
  dependencies: [
    { appKey: "platform", reason: "Uses Platform app registry, security, data/RLS, party, document, event, audit, search, report, print, dashboard, import/export, and job readiness contracts." },
  ],
  description: "Foundation-only HR app for core identity, employment profiles, positions, legal contracts, lifecycle states, timeline contracts, policy engine, compensation engine, workforce engine, attendance engine, leave/absence foundation, payroll engine, payroll relationship foundation, payroll runtime foundation, payroll inputs runtime foundation, payroll calculation engine foundation, payroll validation locking & closing engine foundation, payslip publishing & employee payroll portal foundation, payroll localization framework, payroll finance bank readiness foundation, payroll portal security readiness foundation, HR action engine, HR action apply engine, HR workflow & approval binding, HR template & lifecycle, HR assignment engine, HR job architecture foundation, HR skills & competency foundation, and HR workforce planning foundation contracts.",
  experiences: ["erp"],
  featureFlags: [],
  icon: "id-card",
  key: "hr",
  name: "HR Core Foundation",
  navigation: [
    {
      appKey: "hr",
      href: "/erp/hr",
      key: "hr.launcher",
      kind: "app",
      label: "HR",
      order: 50,
      placement: "app-launcher",
      requiredPermission: HR_PERMISSIONS.view,
      supportedExperiences: ["erp"],
    },
    {
      appKey: "hr",
      href: "/erp/hr",
      key: "hr.sidebar",
      label: "HR Core Foundation",
      order: 50,
      placement: "contextual-sidebar",
      requiredPermission: HR_PERMISSIONS.view,
      supportedExperiences: ["erp"],
    },
  ],
  permissions: [
    HR_PERMISSIONS.view,
    HR_PERMISSIONS.employeesView,
    HR_PERMISSIONS.employmentProfilesView,
    HR_PERMISSIONS.positionsView,
    HR_PERMISSIONS.contractsView,
    HR_PERMISSIONS.policiesView,
    HR_PERMISSIONS.compensationView,
    HR_PERMISSIONS.salaryPackagesView,
    HR_PERMISSIONS.workforceView,
    HR_PERMISSIONS.shiftsView,
    HR_PERMISSIONS.calendarsView,
    HR_PERMISSIONS.attendanceView,
    HR_PERMISSIONS.leaveView,
    HR_PERMISSIONS.payrollView,
    HR_PERMISSIONS.payrollRelationshipsView,
    HR_PERMISSIONS.payrollBatchesView,
    HR_PERMISSIONS.payslipsView,
    HR_PERMISSIONS.actionsView,
    HR_PERMISSIONS.jobsView,
    HR_PERMISSIONS.skillsView,
  ],
  prints: [
    { key: "hr.foundation.readiness-print", requiredPermission: HR_PERMISSIONS.reportsView, type: "print" },
  ],
  quickActions: [],
  reports: [
    { key: "hr.foundation.readiness", requiredPermission: HR_PERMISSIONS.reportsView, type: "report" },
  ],
  notifications: [
    { key: "hr.foundation.notification-readiness", requiredPermission: HR_PERMISSIONS.view, type: "notification" },
  ],
  routes: [
    {
      experience: "erp",
      key: "hr.home",
      label: "HR Core Foundation",
      path: "/erp/hr",
      requiredPermission: HR_PERMISSIONS.view,
    },
  ],
  sensitiveData: "restricted",
  settings: [
    { key: "hr.foundation.settings", requiredPermission: HR_PERMISSIONS.manage, type: "setting" },
  ],
  statuses: ["draft", "active", "inactive", "locked", "archived"],
  version: "1.0.0",
} satisfies AppManifest);
